set(MEMOCHAT_QML_APP_SOURCES
    app/main.cpp
    app/MainLogging.cpp
    app/MainPlatformBootstrap.cpp
    app/MainQmlTypeRegistry.cpp
    app/MainQmlEngineSetup.cpp
    app/MainQmlWindowLoader.cpp
    app/MainRuntimeConfig.cpp
    app/MainWindowEffects.cpp
    app/MainWindowHooks.cpp
    app/AppController.cpp
    app/AppSessionCoordinator.cpp
    app/SessionAuthCoordinator.cpp
    app/SessionAuthCoordinatorCommands.cpp
    app/SessionAuthCoordinatorLoginResponse.cpp
    app/SessionAuthCoordinatorAuthResponses.cpp
    app/SessionChatEntryCoordinator.cpp
    app/SessionRelationBootstrap.cpp
    app/RegisterCountdownController.cpp
    app/AppControllerAuth.cpp
    app/AppControllerAuthResponses.cpp
    app/CallCoordinator.cpp
    app/CallCoordinatorPayloadPolicy.cpp
    app/AppChatConnectionCoordinator.cpp
    app/AppChatConnectionPolicy.cpp
    app/ContactCoordinatorShell.cpp
    app/AppControllerContactEvents.cpp
    app/AppControllerDialogListEvents.cpp
    app/AppControllerDialogState.cpp
    app/AppControllerDialogCommands.cpp
    app/GroupCoordinator.cpp
    app/MediaCoordinator.cpp
    app/ProfileCoordinator.cpp
    app/AppControllerGroupCommands.cpp
    app/AppControllerGroupPayloads.cpp
    app/AppControllerGroupManagement.cpp
    app/AppControllerModels.cpp
    app/AppControllerDialogModels.cpp
    app/AppControllerPrivateHistory.cpp
    app/AppControllerReadAcks.cpp
    app/AppControllerPrivateSelection.cpp
    app/AppControllerContactSelection.cpp
    app/AppControllerGroupSelection.cpp
    app/AppControllerDialogSelection.cpp
    app/AppControllerPagination.cpp
    app/AppControllerNavigation.cpp
    app/AppControllerUiProperties.cpp
    app/AppControllerUserProperties.cpp
    app/AppControllerGroupProperties.cpp
    app/AppControllerModelProperties.cpp
    app/AppControllerContactState.cpp
    app/AppControllerStatusState.cpp
    app/AppControllerLoadingState.cpp
    app/AppControllerDialogRuntimeState.cpp
    app/AppControllerProfileState.cpp
    app/AppControllerBootstrapState.cpp
    app/AppControllerProfileCommands.cpp
    app/AppControllerGroupEvents.cpp
    app/AppControllerGroupResponses.cpp
    app/AppControllerGroupResponseErrors.cpp
    app/AppControllerGroupManagementResponses.cpp
    app/AppControllerGroupHistoryResponses.cpp
    app/AppControllerGroupMessageResponses.cpp
    app/AppControllerPrivateMessageResponses.cpp
    app/AppControllerDialogMetaResponses.cpp
    app/AppControllerMedia.cpp
    app/AppControllerPendingAttachments.cpp
    app/AppControllerMediaUploadQueue.cpp
    app/AppControllerMessageDispatch.cpp
    app/AppControllerPrivateEvents.cpp
    app/AppControllerMessageStatus.cpp
    app/AppControllerPrivateHistoryResponses.cpp
    app/AppControllerPrivateMessageEvents.cpp
    app/AppControllerPrivateReadEvents.cpp
    app/AppControllerChatBootstrap.cpp
    app/AppControllerRelationBootstrap.cpp
)

set(MEMOCHAT_QML_APP_HEADERS
    app/MainLogging.h
    app/MainPlatformBootstrap.h
    app/MainQmlBootstrap.h
    app/MainRuntimeConfig.h
    app/MainWindowEffects.h
    app/MainWindowHooks.h
    app/AppController.h
    app/AppControllerConnectionState.h
    app/AppChatConnectionPolicy.h
    app/CallCoordinatorPayloadPolicy.h
    app/AppControllerDialogStateData.h
    app/AppControllerGroupState.h
    app/AppControllerGroupPayloads.h
    app/AppControllerPendingSendState.h
    app/AppControllerRuntimeState.h
    app/AppControllerUserState.h
    app/AppCoordinators.h
)
