set(MEMOCHAT_QML_FEATURE_SOURCES
    features/auth/AuthController.cpp
    features/call/CallController.cpp
    features/call/CallSessionModel.cpp
    features/call/LivekitBridge.cpp
    features/chat/ChatController.cpp
    features/chat/ChatDispatchService.cpp
    features/chat/ChatCacheMessageCodec.cpp
    features/chat/ChatMessageModelContent.cpp
    features/chat/ChatMessageModel.cpp
    features/chat/ChatMessageModelMutations.cpp
    features/chat/ChatMessageModelPresentation.cpp
    features/chat/ChatMessageModelQueries.cpp
    features/chat/ConversationSyncService.cpp
    features/chat/DialogListEntryBuilder.cpp
    features/chat/DialogListService.cpp
    features/chat/GroupChatCacheStore.cpp
    features/chat/MessageContentCodec.cpp
    features/chat/MessagePayloadService.cpp
    features/chat/PrivateChatCacheStore.cpp
    features/contact/ApplyRequestModel.cpp
    features/contact/ContactController.cpp
    features/contact/FriendListModel.cpp
    features/contact/FriendListModelMutations.cpp
    features/contact/FriendListModelState.cpp
    features/contact/FriendListModelQueries.cpp
    features/contact/SearchResultModel.cpp
    features/profile/ProfileController.cpp
    features/moments/MomentsController.cpp
    features/moments/MomentsEntryParser.cpp
    features/moments/MomentsPublishPayload.cpp
    features/moments/MomentsControllerParsing.cpp
    features/moments/MomentsControllerPublish.cpp
    features/moments/MomentsControllerRequests.cpp
    features/moments/MomentsControllerResponses.cpp
    features/moments/MomentsResponseParser.cpp
    features/moments/MomentsModel.cpp
    features/moments/MomentsModelMutations.cpp
    features/moments/MomentsModelQueries.cpp
    features/agent/AgentControllerChat.cpp
    features/agent/AgentController.cpp
    features/agent/AgentGameClient.cpp
    features/agent/AgentControllerGameNetwork.cpp
    features/agent/AgentControllerGameResponses.cpp
    features/agent/AgentControllerGameRooms.cpp
    features/agent/AgentControllerGameTemplates.cpp
    features/agent/AgentControllerAgentTasks.cpp
    features/agent/AgentControllerKnowledge.cpp
    features/agent/AgentControllerMemory.cpp
    features/agent/AgentControllerModels.cpp
    features/agent/AgentControllerSessions.cpp
    features/agent/AgentControllerState.cpp
    features/agent/AgentControllerStream.cpp
    features/agent/AgentMessageModel.cpp
    features/agent/AgentRequestTracker.cpp
    features/agent/AgentStreamClient.cpp
    features/pet/PetAssetSettings.cpp
    features/pet/PetAssetSettingsAvatar.cpp
    features/pet/PetAssetSettingsPersistence.cpp
    features/pet/PetAssetSettingsState.cpp
    features/pet/PetAssetSettingsVoiceTraining.cpp
    features/pet/PetAvatarPathUtils.cpp
    features/pet/PetAvatarResolver.cpp
    features/pet/PetController.cpp
    features/pet/PetControllerNetwork.cpp
    features/pet/PetControllerSession.cpp
    features/pet/PetControllerState.cpp
    features/pet/PetControllerVoiceRuntime.cpp
    features/pet/PetControllerVoiceTraining.cpp
    features/pet/PetVisionFrameEncoder.cpp
    features/pet/PetControllerVision.cpp
    features/pet/PetControllerWindowsBridge.cpp
    features/pet/PetModel.cpp
    features/pet/PetSpeechSynthesizer.cpp
    features/r18/R18Controller.cpp
    features/r18/R18ControllerNetwork.cpp
    features/r18/R18ControllerResponses.cpp
    features/r18/R18ControllerSources.cpp
    features/r18/R18ControllerState.cpp
    features/r18/R18ListModel.cpp
)

set(MEMOCHAT_QML_FEATURE_HEADERS
    features/auth/AuthController.h
    features/call/CallController.h
    features/call/CallSessionModel.h
    features/call/LivekitBridge.h
    features/chat/ChatController.h
    features/chat/ChatDispatchService.h
    features/chat/ChatCacheMessageCodec.h
    features/chat/ChatMessageModel.h
    features/chat/ConversationSyncService.h
    features/chat/DialogListEntryBuilder.h
    features/chat/DialogListService.h
    features/chat/DialogListTypes.h
    features/chat/GroupChatCacheStore.h
    features/chat/MessageContentCodec.h
    features/chat/MessagePayloadService.h
    features/chat/PrivateChatCacheStore.h
    features/contact/ApplyRequestModel.h
    features/contact/ContactController.h
    features/contact/FriendListModel.h
    features/contact/SearchResultModel.h
    features/profile/ProfileController.h
    features/moments/MomentsController.h
    features/moments/MomentsEntryParser.h
    features/moments/MomentsPublishPayload.h
    features/moments/MomentsResponseParser.h
    features/moments/MomentsModel.h
    features/agent/AgentController.h
    features/agent/AgentGameClient.h
    features/agent/AgentMessageModel.h
    features/agent/AgentNetworkRequestUtils.h
    features/agent/AgentRequestTypes.h
    features/agent/AgentRequestTracker.h
    features/agent/AgentStreamClient.h
    features/pet/PetAssetSettings.h
    features/pet/PetAssetSettingsPrivate.h
    features/pet/PetAvatarPathUtils.h
    features/pet/PetAvatarResolver.h
    features/pet/PetController.h
    features/pet/PetNetworkRequestUtils.h
    features/pet/PetControllerPrivate.h
    features/pet/PetVisionFrameEncoder.h
    features/pet/PetVisionFrameUtils.h
    features/pet/PetWindowsBridgeUtils.h
    features/pet/PetModel.h
    features/pet/PetSpeechSynthesizer.h
    features/r18/R18Controller.h
    features/r18/R18ControllerPrivate.h
    features/r18/R18ListModel.h
)
