CREATE SCHEMA IF NOT EXISTS "memo";
SET search_path TO "memo", public;

CREATE TABLE IF NOT EXISTS chat_event_outbox (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id varchar(64) NOT NULL,
    topic varchar(128) NOT NULL,
    partition_key varchar(128) NOT NULL,
    payload_json jsonb NOT NULL,
    status smallint NOT NULL DEFAULT 0,
    retry_count integer NOT NULL DEFAULT 0,
    next_retry_at bigint NOT NULL DEFAULT 0,
    created_at bigint NOT NULL DEFAULT 0,
    published_at bigint,
    last_error text NOT NULL DEFAULT '',
    CONSTRAINT uq_chat_event_outbox_event_id UNIQUE (event_id)
);

CREATE INDEX IF NOT EXISTS idx_chat_event_outbox_status_retry
    ON chat_event_outbox(status, next_retry_at, id);

CREATE INDEX IF NOT EXISTS idx_chat_event_outbox_topic_status
    ON chat_event_outbox(topic, status, id);
