#!/usr/bin/env bash
set -euo pipefail

BASE_URL="http://127.0.0.1:8096/pet"
IMAGE_FILE=""
UID_VALUE="7"
UID_EXPLICIT="false"
PROFILE_ID="default"
PERSONA="memo-pet"
PROVIDER="scripted"
PYTHON_BIN="${PYTHON_BIN:-python3}"
FULL_VISUAL_LAYER="false"
KEEP_GENERATED_FRAME="false"
ALLOW_CAPTURE_DISABLED="false"
GENERATED_DIR=""

cleanup() {
  if [[ -n "$GENERATED_DIR" && "$KEEP_GENERATED_FRAME" != "true" ]]; then
    case "$GENERATED_DIR" in
      /tmp/memochat-pet-vision.*)
        rm -rf -- "$GENERATED_DIR"
        ;;
    esac
  fi
}
trap cleanup EXIT

usage() {
  cat <<'EOF'
Usage: smoke_pet_vision_wsl.sh [--base-url URL] [--image-file PATH] [--full-visual-layer]

Checks AIOrchestrator pet vision diagnostics. When --image-file is provided,
creates a pet session and uploads one PNG/JPEG frame to /pet/sessions/{id}/capture.
With --full-visual-layer, creates a synthetic test user and validates diagnostics,
uploaded-frame capture, rich visual observation, agent input, visual boundary cases,
session listing, and interrupt behavior.

Options:
  --base-url URL              Pet API base URL, default http://127.0.0.1:8096/pet
  --image-file PATH           PNG/JPEG file to base64 upload for capture smoke
  --full-visual-layer         Run the full synthetic test-user visual layer flow
  --allow-capture-disabled    Continue boundary/input checks if /capture returns 503
  --keep-generated-frame      Keep the synthetic PNG generated by --full-visual-layer
  --uid UID                   Session uid, default 7, or 909007 with --full-visual-layer
  --profile-id ID             Session profile id, default "default"
  --help                      Show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --base-url)
      BASE_URL="${2:?missing --base-url value}"
      shift 2
      ;;
    --image-file)
      IMAGE_FILE="${2:?missing --image-file value}"
      shift 2
      ;;
    --uid)
      UID_VALUE="${2:?missing --uid value}"
      UID_EXPLICIT="true"
      shift 2
      ;;
    --profile-id)
      PROFILE_ID="${2:?missing --profile-id value}"
      shift 2
      ;;
    --full-visual-layer)
      FULL_VISUAL_LAYER="true"
      shift
      ;;
    --allow-capture-disabled)
      ALLOW_CAPTURE_DISABLED="true"
      shift
      ;;
    --keep-generated-frame)
      KEEP_GENERATED_FRAME="true"
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1" >&2
    exit 2
  fi
}

require_cmd curl
require_cmd "$PYTHON_BIN"

BASE_URL="${BASE_URL%/}"
if [[ "$FULL_VISUAL_LAYER" == "true" && "$UID_EXPLICIT" != "true" ]]; then
  UID_VALUE="909007"
fi

print_json() {
  if ! printf '%s\n' "$1" | "$PYTHON_BIN" -m json.tool; then
    printf '%s\n' "$1"
  fi
}

make_session_body() {
  "$PYTHON_BIN" - "$UID_VALUE" "$1" "$PERSONA" "$PROVIDER" <<'PY'
import json
import sys

uid, profile_id, persona, provider = sys.argv[1:5]
print(json.dumps({
    "uid": int(uid),
    "profile_id": profile_id,
    "persona": persona,
    "provider": provider,
}, ensure_ascii=False))
PY
}

extract_session_id() {
  JSON_PAYLOAD="$1" "$PYTHON_BIN" - <<'PY'
import json
import os

print(json.loads(os.environ["JSON_PAYLOAD"])["session"]["session_id"])
PY
}

create_session() {
  local profile_id="$1"
  local create_body
  create_body="$(make_session_body "$profile_id")"

  echo "[pet-vision-smoke] POST ${BASE_URL}/sessions (${profile_id}, uid=${UID_VALUE})"
  SESSION_RESPONSE="$(curl -fsS -H 'Content-Type: application/json' -d "$create_body" "${BASE_URL}/sessions")"
  print_json "$SESSION_RESPONSE"
  SESSION_ID="$(extract_session_id "$SESSION_RESPONSE")"
}

generate_synthetic_png() {
  local output_path="$1"
  "$PYTHON_BIN" - "$output_path" <<'PY'
import binascii
import math
import struct
import sys
import zlib
from pathlib import Path

path = Path(sys.argv[1])
width, height = 320, 240
rows = []

def inside_circle(x, y, cx, cy, radius):
    return (x - cx) ** 2 + (y - cy) ** 2 <= radius ** 2

for y in range(height):
    row = bytearray()
    for x in range(width):
        r = int(232 + 12 * x / width)
        g = int(238 + 10 * y / height)
        b = 242
        if inside_circle(x, y, 150, 92, 54):
            r, g, b = 246, 204, 172
        if inside_circle(x, y, 130, 82, 6) or inside_circle(x, y, 170, 82, 6):
            r, g, b = 34, 42, 52
        if 128 <= x <= 174 and 112 <= y <= 130:
            curve = 120 + 6 * math.sin((x - 128) / 46 * math.pi)
            if abs(y - curve) <= 2:
                r, g, b = 190, 69, 86
        if 38 <= x <= 76 and 146 <= y <= 196:
            r, g, b = 90, 157, 214
        if 76 <= x <= 92 and 160 <= y <= 184:
            r, g, b = 70, 130, 184
        if 178 <= x <= 294 and 168 <= y <= 206:
            r, g, b = 44, 53, 65
        if 186 <= x <= 284 and 176 <= y <= 196 and (x // 10 + y // 8) % 2 == 0:
            r, g, b = 70, 81, 96
        row.extend((r, g, b))
    rows.append(b"\x00" + bytes(row))

def chunk(kind, data):
    crc = binascii.crc32(kind + data) & 0xFFFFFFFF
    return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", crc)

raw = b"".join(rows)
png = (
    b"\x89PNG\r\n\x1a\n"
    + chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0))
    + chunk(b"IDAT", zlib.compress(raw, 9))
    + chunk(b"IEND", b"")
)
path.write_bytes(png)
print(path)
PY
}

make_capture_body() {
  "$PYTHON_BIN" - "$1" <<'PY'
import base64
import json
import struct
import sys
from pathlib import Path

path = Path(sys.argv[1])
data = path.read_bytes()
mime = "application/octet-stream"
width = 0
height = 0
if data.startswith(b"\x89PNG\r\n\x1a\n") and len(data) >= 24:
    mime = "image/png"
    width, height = struct.unpack(">II", data[16:24])
elif data.startswith(b"\xff\xd8"):
    mime = "image/jpeg"
    i = 2
    while i + 9 < len(data):
        while i < len(data) and data[i] == 0xff:
            i += 1
        marker = data[i] if i < len(data) else 0
        i += 1
        if marker in {0xc0, 0xc1, 0xc2, 0xc3, 0xc5, 0xc6, 0xc7, 0xc9, 0xca, 0xcb, 0xcd, 0xce, 0xcf}:
            height, width = struct.unpack(">HH", data[i + 3:i + 7])
            break
        if i + 2 > len(data):
            break
        segment_len = struct.unpack(">H", data[i:i + 2])[0]
        i += max(segment_len, 2)
print(json.dumps({
    "frame_base64": base64.b64encode(data).decode("ascii"),
    "frame_mime": mime,
    "frame_width": width,
    "frame_height": height,
    "include_frame": False,
    "metadata": {"source": "uploaded_frame", "file_name": path.name, "test_user": True},
}, ensure_ascii=False))
PY
}

make_segment_capture_body() {
  "$PYTHON_BIN" - "$1" <<'PY'
import base64
import json
import struct
import sys
from pathlib import Path

path = Path(sys.argv[1])
data = path.read_bytes()
mime = "application/octet-stream"
width = 0
height = 0
if data.startswith(b"\x89PNG\r\n\x1a\n") and len(data) >= 24:
    mime = "image/png"
    width, height = struct.unpack(">II", data[16:24])
elif data.startswith(b"\xff\xd8"):
    mime = "image/jpeg"
    i = 2
    while i + 9 < len(data):
        while i < len(data) and data[i] == 0xff:
            i += 1
        marker = data[i] if i < len(data) else 0
        i += 1
        if marker in {0xc0, 0xc1, 0xc2, 0xc3, 0xc5, 0xc6, 0xc7, 0xc9, 0xca, 0xcb, 0xcd, 0xce, 0xcf}:
            height, width = struct.unpack(">HH", data[i + 3:i + 7])
            break
        if i + 2 > len(data):
            break
        segment_len = struct.unpack(">H", data[i:i + 2])[0]
        i += max(segment_len, 2)
encoded = base64.b64encode(data).decode("ascii")
frames = [
    {
        "frame_base64": encoded,
        "frame_mime": mime,
        "frame_width": width,
        "frame_height": height,
        "t_ms": t_ms,
        "metadata": {"source": "synthetic_segment", "index": index},
    }
    for index, t_ms in enumerate((0, 1500, 3000))
]
print(json.dumps({
    "segment_id": f"smoke-segment-{path.stem}",
    "duration_ms": 3000,
    "include_frame": False,
    "frames": frames,
    "metadata": {"source": "uploaded_segment", "file_name": path.name, "test_user": True},
}, ensure_ascii=False))
PY
}

post_json_capture() {
  local url="$1"
  local body="$2"
  local raw
  raw="$(curl -sS -H 'Content-Type: application/json' -d "$body" -w $'\n%{http_code}' "$url")"
  HTTP_STATUS="${raw##*$'\n'}"
  HTTP_BODY="${raw%$'\n'*}"
}

post_json_ok() {
  local url="$1"
  local body="$2"
  HTTP_BODY="$(curl -fsS -H 'Content-Type: application/json' -d "$body" "$url")"
}

assert_capture_payload() {
  JSON_PAYLOAD="$1" "$PYTHON_BIN" - "$2" <<'PY'
import json
import os
import sys

payload = json.loads(os.environ["JSON_PAYLOAD"])
session_id = sys.argv[1]
if payload.get("code") != 0:
    raise SystemExit("capture response code was not 0")
event = payload["event"]
observation = payload["observation"]
if event.get("type") != "pet.control":
    raise SystemExit("capture event type was not pet.control")
if observation.get("type") != "pet.observation":
    raise SystemExit("capture observation type was not pet.observation")
if event.get("session_id") != session_id or observation.get("session_id") != session_id:
    raise SystemExit("capture session_id mismatch")
event_privacy = event["privacy"]
observation_privacy = observation["privacy"]
if event_privacy.get("raw_frame_sent") is not False:
    raise SystemExit("event privacy.raw_frame_sent was not false")
if observation_privacy.get("raw_frame_sent") is not False:
    raise SystemExit("observation privacy.raw_frame_sent was not false")
if observation_privacy.get("retention") != "none":
    raise SystemExit("observation privacy.retention was not none")
vision = observation["vision"]
if not vision.get("enabled"):
    raise SystemExit("capture vision.enabled was not true")
if vision.get("source") != "uploaded_frame":
    raise SystemExit(f"capture vision.source was {vision.get('source')!r}, expected uploaded_frame")
frame = vision.get("frame") or {}
if int(frame.get("width") or 0) <= 0 or int(frame.get("height") or 0) <= 0:
    raise SystemExit("capture frame dimensions were missing")
scene = vision.get("scene") or {}
if not scene.get("summary"):
    raise SystemExit("capture scene.summary was missing")
print("[pet-vision-smoke] upload capture privacy/frame/scene contract OK")
PY
}

assert_segment_capture_payload() {
  JSON_PAYLOAD="$1" "$PYTHON_BIN" - "$2" <<'PY'
import json
import os
import sys

payload = json.loads(os.environ["JSON_PAYLOAD"])
session_id = sys.argv[1]
if payload.get("code") != 0:
    raise SystemExit("segment capture response code was not 0")
event = payload["event"]
observation = payload["observation"]
if event.get("type") != "pet.control":
    raise SystemExit("segment capture event type was not pet.control")
if observation.get("type") != "pet.observation":
    raise SystemExit("segment capture observation type was not pet.observation")
if event.get("session_id") != session_id or observation.get("session_id") != session_id:
    raise SystemExit("segment capture session_id mismatch")
event_privacy = event["privacy"]
observation_privacy = observation["privacy"]
if event_privacy.get("raw_frame_sent") is not False:
    raise SystemExit("segment event privacy.raw_frame_sent was not false")
if observation_privacy.get("raw_frame_sent") is not False:
    raise SystemExit("segment observation privacy.raw_frame_sent was not false")
if observation_privacy.get("retention") != "none":
    raise SystemExit("segment observation privacy.retention was not none")
if int(observation_privacy.get("raw_frame_count") or 0) != 3:
    raise SystemExit("segment observation raw_frame_count was not 3")
vision = observation["vision"]
if vision.get("source") != "uploaded_segment":
    raise SystemExit(f"segment vision.source was {vision.get('source')!r}, expected uploaded_segment")
segment = vision.get("segment") or {}
if int(segment.get("frame_count") or 0) != 3:
    raise SystemExit("segment frame_count was not 3")
if int(segment.get("duration_ms") or 0) != 3000:
    raise SystemExit("segment duration_ms was not 3000")
if segment.get("temporal_mode") != "keyframe_segment":
    raise SystemExit("segment temporal_mode was not keyframe_segment")
scene = vision.get("scene") or {}
if not scene.get("summary") or not scene.get("segment"):
    raise SystemExit("segment scene summary/metadata was missing")
print("[pet-vision-smoke] upload segment privacy/frame/scene contract OK")
PY
}

make_visual_observation_body() {
  "$PYTHON_BIN" - "$1" <<'PY'
import json
import sys

kind = sys.argv[1]
vision = {
    "enabled": True,
    "mode": "mediapipe_face_landmarker",
    "face_present": True,
    "attention": "user_face",
    "expression": "smile",
    "confidence": 0.94,
    "pose": {"face_confidence": 0.94, "brightness": 0.62},
    "head_pose": {"yaw": 12.0, "pitch": -4.0, "roll": 3.0},
    "blendshapes": {
        "jawOpen": 0.22,
        "eyeBlinkLeft": 0.1,
        "eyeBlinkRight": 0.1,
        "mouthSmileLeft": 0.8,
        "mouthSmileRight": 0.82,
    },
    "scene": {
        "summary": "画面里有杯子和键盘。",
        "object_labels": ["cup", "keyboard"],
        "object_count": 2,
        "lighting": "ambient",
        "brightness": 0.62,
    },
    "objects": [
        {"label": "cup", "score": 0.88},
        {"label": "keyboard", "score": 0.78},
    ],
    "source": "synthetic_test_user",
    "frame": {"width": 640, "height": 480},
    "captured_at_ms": 1760000000000,
}
if kind == "cooldown":
    vision["expression"] = "surprised"
    vision["blendshapes"] = {"jawOpen": 0.18, "eyeBlinkLeft": 0.02, "eyeBlinkRight": 0.02}
    vision["scene"]["summary"] = "用户刚刚换成惊讶表情。"
elif kind == "low_confidence":
    vision["confidence"] = 0.35
    vision["pose"]["face_confidence"] = 0.35
elif kind == "no_face":
    vision["face_present"] = False
    vision["attention"] = "no_face"
    vision["expression"] = ""
    vision["confidence"] = 0.91
    vision["pose"]["face_confidence"] = 0.91
    vision["scene"]["summary"] = "暂时没有看到用户的脸。"
elif kind != "high":
    raise SystemExit(f"unknown observation kind: {kind}")

print(json.dumps({
    "type": "pet.observation",
    "audio": {"vad": "idle", "rms": 0.0, "interrupt": False},
    "vision": vision,
    "privacy": {"raw_frame_sent": False, "raw_audio_recorded": False, "retention": "none"},
}, ensure_ascii=False))
PY
}

assert_visual_observation_payload() {
  JSON_PAYLOAD="$1" "$PYTHON_BIN" - "$2" "$3" <<'PY'
import json
import os
import sys

payload = json.loads(os.environ["JSON_PAYLOAD"])
session_id, expected = sys.argv[1:3]
if payload.get("code") != 0:
    raise SystemExit("observation response code was not 0")
event = payload["event"]
if event.get("type") != "pet.control" or event.get("session_id") != session_id:
    raise SystemExit("observation event contract mismatch")
summary = event.get("debug", {}).get("visual_summary", {})
speech = event.get("speech", {}).get("text_delta", "")
if event.get("privacy", {}).get("raw_frame_sent") is not False:
    raise SystemExit("observation event raw_frame_sent was not false")
if expected == "high":
    if event.get("action", {}).get("name") != "visual_react":
        raise SystemExit("high-confidence observation did not visual_react")
    if not summary.get("speak"):
        raise SystemExit("high-confidence observation did not speak")
    if "我看到你啦" not in speech or "心情不错" not in speech:
        raise SystemExit("first detected user contextual greeting was not emitted")
    if summary.get("reason") != "first_user_seen":
        raise SystemExit("high-confidence first observation did not use first_user_seen")
    if "杯子和键盘" not in str(summary.get("summary_text") or ""):
        raise SystemExit("high-confidence scene summary was not propagated")
    if event.get("expression") != "smile_soft":
        raise SystemExit("high-confidence expression did not map to smile_soft")
    if event.get("gaze", {}).get("target") != "user_face":
        raise SystemExit("high-confidence gaze target was not user_face")
    if float(event.get("lip_sync", {}).get("value") or 0.0) <= 0.0:
        raise SystemExit("high-confidence visual lip sync was not raised")
else:
    if summary.get("reason") != expected:
        raise SystemExit(f"expected visual_summary.reason={expected}, got {summary.get('reason')!r}")
    if summary.get("speak"):
        raise SystemExit(f"{expected} boundary unexpectedly spoke")
    if speech:
        raise SystemExit(f"{expected} boundary emitted speech text")
print(f"[pet-vision-smoke] visual observation boundary OK: {expected}")
PY
}

make_input_body() {
  "$PYTHON_BIN" - "$UID_VALUE" <<'PY'
import json
import sys

print(json.dumps({
    "uid": int(sys.argv[1]),
    "content": "你刚才看到什么？",
    "model_type": "scripted",
    "model_name": "deterministic",
    "metadata": {"source": "pet_vision_smoke", "expect_visual_summary": True},
}, ensure_ascii=False))
PY
}

assert_input_payload() {
  JSON_PAYLOAD="$1" "$PYTHON_BIN" - "$2" <<'PY'
import json
import os
import sys

payload = json.loads(os.environ["JSON_PAYLOAD"])
session_id = sys.argv[1]
if payload.get("code") != 0:
    raise SystemExit("input response code was not 0")
events = payload.get("events") or []
if len(events) < 3:
    raise SystemExit("input did not return the expected control event sequence")
phases = [event.get("phase") for event in events]
if phases[0] != "listening" or "speaking" not in phases or phases[-1] != "idle":
    raise SystemExit(f"unexpected input phases: {phases}")
if any(event.get("type") != "pet.control" or event.get("session_id") != session_id for event in events):
    raise SystemExit("input event contract mismatch")
if not "".join(event.get("text", {}).get("delta", "") for event in events).strip():
    raise SystemExit("input did not emit text")
if any(event.get("privacy", {}).get("raw_frame_sent") is not False for event in events):
    raise SystemExit("input leaked raw_frame_sent")
print("[pet-vision-smoke] agent input after visual summary OK")
PY
}

assert_interrupt_payload() {
  JSON_PAYLOAD="$1" "$PYTHON_BIN" - "$2" <<'PY'
import json
import os
import sys

payload = json.loads(os.environ["JSON_PAYLOAD"])
session_id = sys.argv[1]
event = payload["event"]
if payload.get("code") != 0 or event.get("session_id") != session_id:
    raise SystemExit("interrupt response contract mismatch")
if event.get("phase") != "interrupted" or event.get("action", {}).get("name") != "interrupt":
    raise SystemExit("interrupt did not emit interrupted control event")
if event.get("motion") != "stop":
    raise SystemExit("interrupt motion was not stop")
print("[pet-vision-smoke] interrupt boundary OK")
PY
}

assert_session_list_payload() {
  JSON_PAYLOAD="$1" "$PYTHON_BIN" - "$2" "$3" <<'PY'
import json
import os
import sys

payload = json.loads(os.environ["JSON_PAYLOAD"])
expected = set(sys.argv[1:3])
sessions = payload.get("sessions") or []
ids = {item.get("session_id") for item in sessions}
missing = expected - ids
if payload.get("code") != 0 or missing:
    raise SystemExit(f"session list missing ids: {sorted(missing)}")
print("[pet-vision-smoke] synthetic test-user session list OK")
PY
}

echo "[pet-vision-smoke] GET ${BASE_URL}/diagnostics/vision"
diagnostics_body="$(curl -fsS "${BASE_URL}/diagnostics/vision")"
print_json "$diagnostics_body"

if [[ "$FULL_VISUAL_LAYER" != "true" && -z "$IMAGE_FILE" ]]; then
  echo "[pet-vision-smoke] no --image-file supplied; diagnostics-only smoke complete"
  exit 0
fi

if [[ "$FULL_VISUAL_LAYER" == "true" && -z "$IMAGE_FILE" ]]; then
  GENERATED_DIR="$(mktemp -d /tmp/memochat-pet-vision.XXXXXX)"
  IMAGE_FILE="${GENERATED_DIR}/synthetic-test-user.png"
  echo "[pet-vision-smoke] generate synthetic frame ${IMAGE_FILE}"
  generate_synthetic_png "$IMAGE_FILE" >/dev/null
fi

if [[ ! -f "$IMAGE_FILE" ]]; then
  echo "Image file not found: $IMAGE_FILE" >&2
  exit 2
fi

if [[ "$FULL_VISUAL_LAYER" == "true" ]]; then
  capture_profile="vision-smoke-capture"
  agent_profile="vision-smoke-agent"
else
  capture_profile="$PROFILE_ID"
  agent_profile="$PROFILE_ID"
fi

create_session "$capture_profile"
capture_session_id="$SESSION_ID"
capture_body="$(make_capture_body "$IMAGE_FILE")"

echo "[pet-vision-smoke] POST ${BASE_URL}/sessions/${capture_session_id}/capture (--image-file)"
post_json_capture "${BASE_URL}/sessions/${capture_session_id}/capture" "$capture_body"
if [[ "$HTTP_STATUS" != "200" ]]; then
  print_json "$HTTP_BODY"
  if [[ "$FULL_VISUAL_LAYER" == "true" && "$ALLOW_CAPTURE_DISABLED" == "true" && "$HTTP_STATUS" == "503" ]]; then
    echo "[pet-vision-smoke] capture returned 503; continuing because --allow-capture-disabled was supplied"
  else
    echo "[pet-vision-smoke] capture failed with HTTP ${HTTP_STATUS}" >&2
    exit 1
  fi
else
  print_json "$HTTP_BODY"
  assert_capture_payload "$HTTP_BODY" "$capture_session_id"
  segment_body="$(make_segment_capture_body "$IMAGE_FILE")"
  echo "[pet-vision-smoke] POST ${BASE_URL}/sessions/${capture_session_id}/capture-segment (--image-file keyframes)"
  post_json_capture "${BASE_URL}/sessions/${capture_session_id}/capture-segment" "$segment_body"
  if [[ "$HTTP_STATUS" != "200" ]]; then
    print_json "$HTTP_BODY"
    echo "[pet-vision-smoke] segment capture failed with HTTP ${HTTP_STATUS}" >&2
    exit 1
  fi
  print_json "$HTTP_BODY"
  assert_segment_capture_payload "$HTTP_BODY" "$capture_session_id"
fi

if [[ "$FULL_VISUAL_LAYER" != "true" ]]; then
  exit 0
fi

create_session "$agent_profile"
agent_session_id="$SESSION_ID"

for observation_kind in high cooldown low_confidence no_face; do
  observation_body="$(make_visual_observation_body "$observation_kind")"
  echo "[pet-vision-smoke] POST ${BASE_URL}/sessions/${agent_session_id}/observation (${observation_kind})"
  post_json_ok "${BASE_URL}/sessions/${agent_session_id}/observation" "$observation_body"
  print_json "$HTTP_BODY"
  if [[ "$observation_kind" == "cooldown" ]]; then
    assert_visual_observation_payload "$HTTP_BODY" "$agent_session_id" "cooldown"
  else
    assert_visual_observation_payload "$HTTP_BODY" "$agent_session_id" "$observation_kind"
  fi

  if [[ "$observation_kind" == "cooldown" ]]; then
    input_body="$(make_input_body)"
    echo "[pet-vision-smoke] POST ${BASE_URL}/sessions/${agent_session_id}/input"
    post_json_ok "${BASE_URL}/sessions/${agent_session_id}/input" "$input_body"
    print_json "$HTTP_BODY"
    assert_input_payload "$HTTP_BODY" "$agent_session_id"
  fi
done

echo "[pet-vision-smoke] POST ${BASE_URL}/sessions/${agent_session_id}/interrupt"
post_json_ok "${BASE_URL}/sessions/${agent_session_id}/interrupt" "{}"
print_json "$HTTP_BODY"
assert_interrupt_payload "$HTTP_BODY" "$agent_session_id"

echo "[pet-vision-smoke] GET ${BASE_URL}/sessions?uid=${UID_VALUE}"
sessions_body="$(curl -fsS "${BASE_URL}/sessions?uid=${UID_VALUE}")"
print_json "$sessions_body"
assert_session_list_payload "$sessions_body" "$capture_session_id" "$agent_session_id"

echo "[pet-vision-smoke] full synthetic test-user visual layer smoke complete"
