apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://memochat-prometheus:9090
    isDefault: true
    editable: false
  - name: InfluxDB
    uid: influxdb
    type: influxdb
    access: proxy
    url: http://memochat-influxdb:8086
    jsonData:
      version: Flux
      httpMode: POST
      organization: memochat
      defaultBucket: metrics
    secureJsonData:
      token: ${MEMOCHAT_INFLUXDB_GRAFANA_TOKEN}
    editable: false
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://memochat-loki:3100
    editable: false
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://memochat-tempo:3200
    editable: false
