#include "PostgresDao.h"
#include "ConfigMgr.h"
#include "SnowflakeUtil.h"
#include <algorithm>
#include <cctype>
#include <cstdlib>
#include <random>
#include <string_view>

namespace {
std::string BuildConnectionString() {
	auto& cfg = ConfigMgr::Inst();
	const auto host = cfg["Postgres"]["Host"];
	const auto port = cfg["Postgres"]["Port"];
	const auto pwd = cfg["Postgres"]["Passwd"];
	const auto database = cfg["Postgres"]["Database"];
	const auto schema = cfg["Postgres"]["Schema"];
	const auto user = cfg["Postgres"]["User"];
	const auto sslmode = cfg["Postgres"]["SslMode"];
	std::string conn = "host=" + host +
		" port=" + port +
		" user=" + user +
		" password=" + pwd +
		" dbname=" + database +
		" sslmode=" + (sslmode.empty() ? "disable" : sslmode) +
		" connect_timeout=3";
	return conn;
}

std::string PostgresSchemaName() {
	auto& cfg = ConfigMgr::Inst();
	const auto schema = cfg["Postgres"]["Schema"];
	return schema.empty() ? "public" : schema;
}

std::string QuotePgIdent(std::string_view ident) {
	std::string out = "\"";
	for (char ch : ident) {
		if (ch == '"') {
			out += "\"\"";
		} else {
			out += ch;
		}
	}
	out += "\"";
	return out;
}

std::string PgTable(std::string_view table) {
	return QuotePgIdent(PostgresSchemaName()) + "." + QuotePgIdent(table);
}

int PostgresPoolSize() {
	auto& cfg = ConfigMgr::Inst();
	const auto configured = cfg["Postgres"]["PoolSize"];
	if (configured.empty()) {
		return 5;
	}
	return std::clamp(std::atoi(configured.c_str()), 1, 20);
}

std::string DecodeLegacyXorPwd(const std::string& input) {
	unsigned int xor_code = static_cast<unsigned int>(input.size() % 255);
	std::string decoded = input;
	for (size_t i = 0; i < decoded.size(); ++i) {
		decoded[i] = static_cast<char>(static_cast<unsigned char>(decoded[i]) ^ xor_code);
	}
	return decoded;
}
}

PostgresDao::PostgresDao()
{
	pool_.reset(new PostgresPool(BuildConnectionString(), PostgresSchemaName(), PostgresPoolSize()));
	EnsureMomentsCommentLikeTable();
	WarmupAuthQueries();
}

PostgresDao::~PostgresDao() {
	pool_->Close();
}

void PostgresDao::EnsureMomentsCommentLikeTable() {
	auto con = pool_->getConnection();
	if (con == nullptr) {
		return;
	}

	Defer defer([this, &con]() {
		pool_->returnConnection(std::move(con));
	});

	try {
		pqxx::work txn(*con->_con);
		txn.exec0(
			"CREATE TABLE IF NOT EXISTS moments_comment_like ("
			"id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
			"comment_id bigint NOT NULL,"
			"uid integer NOT NULL,"
			"created_at bigint NOT NULL DEFAULT 0,"
			"CONSTRAINT uq_moments_comment_like UNIQUE (comment_id, uid)"
			")");
		txn.exec0("CREATE INDEX IF NOT EXISTS idx_moments_comment_like_comment_id ON moments_comment_like(comment_id)");
		txn.exec0("CREATE INDEX IF NOT EXISTS idx_moments_comment_like_uid ON moments_comment_like(uid)");
		txn.commit();
	}
	catch (const std::exception& e) {
		std::cerr << "EnsureMomentsCommentLikeTable PostgreSQL exception: " << e.what() << std::endl;
	}
}

int PostgresDao::RegUser(const std::string& name, const std::string& email, const std::string& pwd)
{
	return RegUserTransaction(name, email, pwd, ":/res/head_1.jpg");
}

int PostgresDao::RegUserTransaction(
	const std::string& name,
	const std::string& email,
	const std::string& pwd,
	const std::string& icon) {
	auto con = pool_->getConnection();
	if (con == nullptr) {
		return -1;
	}

	Defer defer([this, &con]() {
		pool_->returnConnection(std::move(con));
	});

	try {
		pqxx::work txn(*con->_con);
		const auto exists = txn.exec_params(
			"SELECT 1 FROM \"user\" WHERE email = $1 OR name = $2 LIMIT 1",
			email,
			name);
		if (!exists.empty()) {
			txn.commit();
			std::cout << "user " << name << " or email " << email << " exist" << std::endl;
			return 0;
		}

		const int new_id = txn.exec1("SELECT COALESCE(MAX(id), 1000) + 1 FROM user_id")[0].as<int>();
		txn.exec0("DELETE FROM user_id");
		txn.exec_params0("INSERT INTO user_id(id) VALUES ($1)", new_id);

		std::string user_public_id;
		for (int i = 0; i < 20; ++i) {
			user_public_id = GenerateUserPublicId();
			const auto rows = txn.exec_params(
				"SELECT 1 FROM \"user\" WHERE user_id = $1 LIMIT 1",
				user_public_id);
			if (rows.empty()) {
				break;
			}
			user_public_id.clear();
		}

		if (user_public_id.empty()) {
			std::cout << "generate user_public_id failed" << std::endl;
			return -1;
		}

		const std::string pwd_stored = DecodeLegacyXorPwd(pwd);
		txn.exec_params0(
			"INSERT INTO \"user\"(uid, name, email, pwd, nick, icon, user_id) "
			"VALUES ($1, $2, $3, $4, $5, $6, $7)",
			new_id,
			name,
			email,
			pwd_stored,
			name,
			icon,
			user_public_id);
		txn.commit();
		std::cout << "newuser insert into user success" << std::endl;
		return new_id;
	}
	catch (const std::exception& e) {
		std::cerr << "PostgreSQL exception: " << e.what() << std::endl;
		return -1;
	}
}

bool PostgresDao::CheckEmail(const std::string& name, const std::string& email) {
	auto con = pool_->getConnection();
	if (con == nullptr) {
		return false;
	}

	Defer defer([this, &con]() {
		pool_->returnConnection(std::move(con));
	});

	try {
		pqxx::read_transaction txn(*con->_con);
		const auto rows = txn.exec_params(
			"SELECT email FROM \"user\" WHERE name = $1 LIMIT 1",
			name);
		if (rows.empty()) {
			return false;
		}
		const auto stored_email = rows[0]["email"].c_str() ? rows[0]["email"].c_str() : "";
		return stored_email == email;
	}
	catch (const std::exception& e) {
		std::cerr << "PostgreSQL exception: " << e.what() << std::endl;
		return false;
	}
}

bool PostgresDao::UpdatePwd(const std::string& name, const std::string& newpwd) {
	auto con = pool_->getConnection();
	if (con == nullptr) {
		return false;
	}

	Defer defer([this, &con]() {
		pool_->returnConnection(std::move(con));
	});

	try {
		pqxx::work txn(*con->_con);
		const auto result = txn.exec_params(
			"UPDATE \"user\" SET pwd = $1 WHERE name = $2",
			newpwd,
			name);
		txn.commit();
		std::cout << "Updated rows: " << result.affected_rows() << std::endl;
		return result.affected_rows() > 0;
	}
	catch (const std::exception& e) {
		std::cerr << "PostgreSQL exception: " << e.what() << std::endl;
		return false;
	}
}

bool PostgresDao::UpdateUserProfile(int uid, const std::string& nick, const std::string& desc, const std::string& icon) {
	auto con = pool_->getConnection();
	if (con == nullptr) {
		return false;
	}

	Defer defer([this, &con]() {
		pool_->returnConnection(std::move(con));
	});

	try {
		pqxx::work txn(*con->_con);
		const auto result = txn.exec_params(
			"UPDATE \"user\" SET nick = $1, \"desc\" = $2, icon = $3 WHERE uid = $4",
			nick,
			desc,
			icon,
			uid);
		if (result.affected_rows() > 0) {
			txn.commit();
			return true;
		}

		const auto rows = txn.exec_params(
			"SELECT 1 FROM \"user\" WHERE uid = $1 LIMIT 1",
			uid);
		txn.commit();
		return !rows.empty();
	}
	catch (const std::exception& e) {
		std::cerr << "PostgreSQL exception: " << e.what() << std::endl;
		return false;
	}
}

bool PostgresDao::CheckPwd(const std::string& email, const std::string& pwd, UserInfo& userInfo) {
	auto con = pool_->getConnection();
	if (con == nullptr) {
		std::cout << "CheckPwd PostgreSQL connection unavailable" << std::endl;
		return false;
	}

	Defer defer([this, &con]() {
		pool_->returnConnection(std::move(con));
	});

	try {
		pqxx::read_transaction txn(*con->_con);
		const auto rows = txn.exec_params(
			"SELECT uid, name, email, pwd, user_id, nick, icon, \"desc\", sex "
			"FROM " + PgTable("user") + " WHERE email = $1 LIMIT 1",
			email);
		if (rows.empty()) {
			std::cout << "CheckPwd user not found for email " << email << std::endl;
			return false;
		}

		const auto& row = rows[0];
		const std::string origin_pwd = row["pwd"].c_str() ? row["pwd"].c_str() : "";
		const std::string decoded_pwd = DecodeLegacyXorPwd(origin_pwd);
		if (pwd != origin_pwd && pwd != decoded_pwd) {
			return false;
		}

		userInfo.name = row["name"].c_str() ? row["name"].c_str() : "";
		userInfo.email = row["email"].c_str() ? row["email"].c_str() : "";
		userInfo.uid = row["uid"].as<int>();
		userInfo.user_id = row["user_id"].is_null() ? "" : row["user_id"].c_str();
		userInfo.nick = row["nick"].is_null() ? "" : row["nick"].c_str();
		userInfo.icon = row["icon"].is_null() ? "" : row["icon"].c_str();
		userInfo.desc = row["desc"].is_null() ? "" : row["desc"].c_str();
		userInfo.sex = row["sex"].is_null() ? 0 : row["sex"].as<int>();
		userInfo.pwd = decoded_pwd;
		return true;
	}
	catch (const std::exception& e) {
		std::cerr << "PostgreSQL exception: " << e.what() << std::endl;
		return false;
	}
}

std::string PostgresDao::GetUserPublicId(int uid) {
	auto con = pool_->getConnection();
	if (con == nullptr) {
		return "";
	}

	Defer defer([this, &con]() {
		pool_->returnConnection(std::move(con));
	});

	try {
		pqxx::read_transaction txn(*con->_con);
		const auto rows = txn.exec_params(
			"SELECT user_id FROM \"user\" WHERE uid = $1 LIMIT 1",
			uid);
		if (rows.empty() || rows[0]["user_id"].is_null()) {
			return "";
		}
		return rows[0]["user_id"].c_str();
	}
	catch (const std::exception& e) {
		std::cerr << "PostgreSQL exception: " << e.what() << std::endl;
		return "";
	}
}

void PostgresDao::WarmupAuthQueries() {
	auto con = pool_->getConnection();
	if (con == nullptr) {
		return;
	}

	Defer defer([this, &con]() {
		pool_->returnConnection(std::move(con));
	});

	try {
		pqxx::read_transaction txn(*con->_con);
		txn.exec_params(
			"SELECT uid, name, email, pwd, user_id, nick, icon, \"desc\", sex "
			"FROM \"user\" WHERE email = $1 LIMIT 1",
			"__memochat_warmup__@invalid.local");
		txn.commit();
	}
	catch (const std::exception& e) {
		std::cerr << "[DIAG WarmupAuthQueries] PostgreSQL exception: " << e.what() << "\n" << std::flush;
	}
}

bool PostgresDao::GetCallUserProfile(int uid, CallUserProfile& profile) {
	auto con = pool_->getConnection();
	if (con == nullptr) {
		return false;
	}

	Defer defer([this, &con]() {
		pool_->returnConnection(std::move(con));
	});

	try {
		pqxx::read_transaction txn(*con->_con);
		const auto rows = txn.exec_params(
			"SELECT uid, user_id, name, nick, icon FROM \"user\" WHERE uid = $1 LIMIT 1",
			uid);
		if (rows.empty()) {
			return false;
		}

		const auto& row = rows[0];
		profile.uid = row["uid"].as<int>();
		profile.user_id = row["user_id"].is_null() ? "" : row["user_id"].c_str();
		profile.name = row["name"].is_null() ? "" : row["name"].c_str();
		profile.nick = row["nick"].is_null() ? "" : row["nick"].c_str();
		profile.icon = row["icon"].is_null() ? "" : row["icon"].c_str();
		return true;
	}
	catch (const std::exception& e) {
		std::cerr << "GetCallUserProfile PostgreSQL exception: " << e.what() << std::endl;
		return false;
	}
}

bool PostgresDao::IsFriend(int uid, int peer_uid) {
	auto con = pool_->getConnection();
	if (con == nullptr) {
		return false;
	}

	Defer defer([this, &con]() {
		pool_->returnConnection(std::move(con));
	});

	try {
		pqxx::read_transaction txn(*con->_con);
		const auto rows = txn.exec_params(
			"SELECT 1 FROM friend WHERE self_id = $1 AND friend_id = $2 LIMIT 1",
			uid,
			peer_uid);
		return !rows.empty();
	}
	catch (const std::exception& e) {
		std::cerr << "IsFriend PostgreSQL exception: " << e.what() << std::endl;
		return false;
	}
}

bool PostgresDao::UpsertCallSession(const CallSessionInfo& session) {
	auto con = pool_->getConnection();
	if (con == nullptr) {
		return false;
	}

	Defer defer([this, &con]() {
		pool_->returnConnection(std::move(con));
	});

	try {
		pqxx::work txn(*con->_con);
		const auto result = txn.exec_params(
			"INSERT INTO chat_call_session("
			"call_id, room_name, call_type, caller_uid, callee_uid, state, "
			"started_at_ms, accepted_at_ms, ended_at_ms, expires_at_ms, duration_sec, reason, trace_id, updated_at_ms"
			") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) "
			"ON CONFLICT (call_id) DO UPDATE SET "
			"room_name = EXCLUDED.room_name, call_type = EXCLUDED.call_type, caller_uid = EXCLUDED.caller_uid, "
			"callee_uid = EXCLUDED.callee_uid, state = EXCLUDED.state, started_at_ms = EXCLUDED.started_at_ms, "
			"accepted_at_ms = EXCLUDED.accepted_at_ms, ended_at_ms = EXCLUDED.ended_at_ms, "
			"expires_at_ms = EXCLUDED.expires_at_ms, duration_sec = EXCLUDED.duration_sec, "
			"reason = EXCLUDED.reason, trace_id = EXCLUDED.trace_id, updated_at_ms = EXCLUDED.updated_at_ms",
			session.call_id,
			session.room_name,
			session.call_type,
			session.caller_uid,
			session.callee_uid,
			session.state,
			session.started_at_ms,
			session.accepted_at_ms,
			session.ended_at_ms,
			session.expires_at_ms,
			session.duration_sec,
			session.reason,
			session.trace_id,
			session.updated_at_ms);
		txn.commit();
		return result.affected_rows() > 0;
	}
	catch (const std::exception& e) {
		std::cerr << "UpsertCallSession PostgreSQL exception: " << e.what() << std::endl;
		return false;
	}
}

bool PostgresDao::GetCallSession(const std::string& call_id, CallSessionInfo& session) {
	if (call_id.empty()) {
		return false;
	}

	auto con = pool_->getConnection();
	if (con == nullptr) {
		return false;
	}

	Defer defer([this, &con]() {
		pool_->returnConnection(std::move(con));
	});

	try {
		pqxx::read_transaction txn(*con->_con);
		const auto rows = txn.exec_params(
			"SELECT call_id, room_name, call_type, caller_uid, callee_uid, state, "
			"started_at_ms, accepted_at_ms, ended_at_ms, expires_at_ms, duration_sec, reason, trace_id, updated_at_ms "
			"FROM chat_call_session WHERE call_id = $1 LIMIT 1",
			call_id);
		if (rows.empty()) {
			return false;
		}

		const auto& row = rows[0];
		session.call_id = row["call_id"].is_null() ? "" : row["call_id"].c_str();
		session.room_name = row["room_name"].is_null() ? "" : row["room_name"].c_str();
		session.call_type = row["call_type"].is_null() ? "" : row["call_type"].c_str();
		session.caller_uid = row["caller_uid"].is_null() ? 0 : row["caller_uid"].as<int>();
		session.callee_uid = row["callee_uid"].is_null() ? 0 : row["callee_uid"].as<int>();
		session.state = row["state"].is_null() ? "" : row["state"].c_str();
		session.started_at_ms = row["started_at_ms"].is_null() ? 0 : row["started_at_ms"].as<int64_t>();
		session.accepted_at_ms = row["accepted_at_ms"].is_null() ? 0 : row["accepted_at_ms"].as<int64_t>();
		session.ended_at_ms = row["ended_at_ms"].is_null() ? 0 : row["ended_at_ms"].as<int64_t>();
		session.expires_at_ms = row["expires_at_ms"].is_null() ? 0 : row["expires_at_ms"].as<int64_t>();
		session.duration_sec = row["duration_sec"].is_null() ? 0 : row["duration_sec"].as<int>();
		session.reason = row["reason"].is_null() ? "" : row["reason"].c_str();
		session.trace_id = row["trace_id"].is_null() ? "" : row["trace_id"].c_str();
		session.updated_at_ms = row["updated_at_ms"].is_null() ? 0 : row["updated_at_ms"].as<int64_t>();
		return true;
	}
	catch (const std::exception& e) {
		std::cerr << "GetCallSession PostgreSQL exception: " << e.what() << std::endl;
		return false;
	}
}

bool PostgresDao::InsertMediaAsset(const MediaAssetInfo& asset) {
	auto con = pool_->getConnection();
	if (con == nullptr) {
		return false;
	}

	Defer defer([this, &con]() {
		pool_->returnConnection(std::move(con));
	});

	try {
		pqxx::work txn(*con->_con);
		const auto result = txn.exec_params(
			"INSERT INTO chat_media_asset("
			"media_key, owner_uid, media_type, origin_file_name, mime, size_bytes, "
			"storage_provider, storage_path, created_at_ms, deleted_at_ms, status"
			") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)",
			asset.media_key,
			asset.owner_uid,
			asset.media_type,
			asset.origin_file_name,
			asset.mime,
			asset.size_bytes,
			asset.storage_provider,
			asset.storage_path,
			asset.created_at_ms,
			asset.deleted_at_ms,
			asset.status);
		txn.commit();
		return result.affected_rows() > 0;
	}
	catch (const std::exception& e) {
		std::cerr << "InsertMediaAsset PostgreSQL exception: " << e.what() << std::endl;
		return false;
	}
}

bool PostgresDao::GetMediaAssetByKey(const std::string& media_key, MediaAssetInfo& asset) {
	if (media_key.empty()) {
		return false;
	}

	auto con = pool_->getConnection();
	if (con == nullptr) {
		return false;
	}

	Defer defer([this, &con]() {
		pool_->returnConnection(std::move(con));
	});

	try {
		pqxx::read_transaction txn(*con->_con);
		const auto rows = txn.exec_params(
			"SELECT media_id, media_key, owner_uid, media_type, origin_file_name, mime, size_bytes, "
			"storage_provider, storage_path, created_at_ms, deleted_at_ms, status "
			"FROM chat_media_asset WHERE media_key = $1 LIMIT 1",
			media_key);
		if (rows.empty()) {
			return false;
		}

		const auto& row = rows[0];
		asset.media_id = row["media_id"].as<int64_t>();
		asset.media_key = row["media_key"].is_null() ? "" : row["media_key"].c_str();
		asset.owner_uid = row["owner_uid"].is_null() ? 0 : row["owner_uid"].as<int>();
		asset.media_type = row["media_type"].is_null() ? "" : row["media_type"].c_str();
		asset.origin_file_name = row["origin_file_name"].is_null() ? "" : row["origin_file_name"].c_str();
		asset.mime = row["mime"].is_null() ? "" : row["mime"].c_str();
		asset.size_bytes = row["size_bytes"].is_null() ? 0 : row["size_bytes"].as<int64_t>();
		asset.storage_provider = row["storage_provider"].is_null() ? "" : row["storage_provider"].c_str();
		asset.storage_path = row["storage_path"].is_null() ? "" : row["storage_path"].c_str();
		asset.created_at_ms = row["created_at_ms"].is_null() ? 0 : row["created_at_ms"].as<int64_t>();
		asset.deleted_at_ms = row["deleted_at_ms"].is_null() ? 0 : row["deleted_at_ms"].as<int64_t>();
		asset.status = row["status"].is_null() ? 0 : row["status"].as<int>();
		return true;
	}
	catch (const std::exception& e) {
		std::cerr << "GetMediaAssetByKey PostgreSQL exception: " << e.what() << std::endl;
		return false;
	}
}

std::string PostgresDao::GenerateUserPublicId() {
	return SnowflakeUtil::formatPublicId(SnowflakeUtil::getInstance().nextId(), 'u');
}

bool PostgresDao::GetUserInfo(int uid, UserInfo& user_info) {
	if (uid <= 0) {
		return false;
	}
	auto con = pool_->getConnection();
	if (con == nullptr) {
		return false;
	}

	Defer defer([this, &con]() {
		pool_->returnConnection(std::move(con));
	});

	try {
		pqxx::read_transaction txn(*con->_con);
		const auto rows = txn.exec_params(
			"SELECT uid, name, email, user_id, nick, icon, \"desc\", sex "
			"FROM \"user\" WHERE uid = $1 LIMIT 1",
			uid);
		if (rows.empty()) {
			return false;
		}
		const auto& row = rows[0];
		user_info.uid = row["uid"].as<int>();
		user_info.name = row["name"].is_null() ? "" : row["name"].c_str();
		user_info.email = row["email"].is_null() ? "" : row["email"].c_str();
		user_info.user_id = row["user_id"].is_null() ? "" : row["user_id"].c_str();
		user_info.nick = row["nick"].is_null() ? "" : row["nick"].c_str();
		user_info.icon = row["icon"].is_null() ? "" : row["icon"].c_str();
		user_info.desc = row["desc"].is_null() ? "" : row["desc"].c_str();
		user_info.sex = row["sex"].is_null() ? 0 : row["sex"].as<int>();
		return true;
	}
	catch (const std::exception& e) {
		std::cerr << "GetUserInfo PostgreSQL exception: " << e.what() << std::endl;
		return false;
	}
}

bool PostgresDao::TestProcedure(const std::string& email, int& uid, string& name) {
	auto con = pool_->getConnection();
	if (con == nullptr) {
		std::cout << "TestProcedure PostgreSQL connection unavailable" << std::endl;
		return false;
	}

	Defer defer([this, &con]() {
		pool_->returnConnection(std::move(con));
	});

	try {
		pqxx::read_transaction txn(*con->_con);
		const auto rows = txn.exec_params(
			"SELECT uid, name FROM " + PgTable("user") + " WHERE email = $1 LIMIT 1",
			email);
		if (rows.empty()) {
			std::cout << "TestProcedure user not found for email " << email << std::endl;
			return false;
		}
		uid = rows[0]["uid"].as<int>();
		name = rows[0]["name"].c_str() ? rows[0]["name"].c_str() : "";
		return true;
	}
	catch (const std::exception& e) {
		std::cerr << "TestProcedure PostgreSQL exception: " << e.what() << std::endl;
		return false;
	}
}

bool PostgresDao::AddMoment(const MomentInfo& moment, int64_t* moment_id) {
	auto con = pool_->getConnection();
	if (con == nullptr) {
		return false;
	}

	Defer defer([this, &con]() {
		pool_->returnConnection(std::move(con));
	});

	try {
		pqxx::work txn(*con->_con);
		pqxx::result rows = txn.exec_params(
			"INSERT INTO moments(uid, visibility, location, created_at, like_count, comment_count) "
			"VALUES ($1, $2, $3, $4, $5, $6) RETURNING moment_id",
			moment.uid,
			moment.visibility,
			moment.location,
			moment.created_at,
			moment.like_count,
			moment.comment_count);
		if (moment_id) {
			*moment_id = rows.empty() ? 0 : rows[0]["moment_id"].as<int64_t>();
		}
		txn.commit();
		return true;
	}
	catch (const std::exception& e) {
		std::cerr << "AddMoment PostgreSQL exception: " << e.what() << std::endl;
		return false;
	}
}

bool PostgresDao::GetMomentsFeed(int viewer_uid, int64_t last_moment_id, int limit, int author_uid,
	std::vector<MomentInfo>& moments, bool& has_more) {
	moments.clear();
	has_more = false;
	if (limit <= 0) {
		limit = 20;
	}
	limit = std::min(limit, 50);

	auto con = pool_->getConnection();
	if (con == nullptr) {
		return false;
	}

	Defer defer([this, &con]() {
		pool_->returnConnection(std::move(con));
	});

	try {
		pqxx::read_transaction txn(*con->_con);

		pqxx::result rows;
		if (last_moment_id <= 0) {
			rows = txn.exec_params(R"(
				SELECT m.moment_id, m.uid, m.visibility, m.location, m.created_at,
				       m.like_count, m.comment_count
				FROM moments m
				WHERE m.deleted_at = 0
				  AND ($3 <= 0 OR m.uid = $3)
				  AND (
					m.visibility = 0
					OR m.uid = $1
					OR (
						m.visibility = 1
						AND (
							EXISTS (
								SELECT 1
								FROM friend f
								WHERE ((f.self_id = m.uid AND f.friend_id = $1)
									OR (f.self_id = $1 AND f.friend_id = m.uid))
							)
							OR EXISTS (
								SELECT 1
								FROM friend_apply fa
								WHERE fa.status = 1
								  AND ((fa.from_uid = m.uid AND fa.to_uid = $1)
									OR (fa.from_uid = $1 AND fa.to_uid = m.uid))
							)
						)
					)
				  )
				ORDER BY m.created_at DESC, m.moment_id DESC
				LIMIT $2
			)", viewer_uid, limit + 1, author_uid);
		}
		else {
			rows = txn.exec_params(R"(
				SELECT m.moment_id, m.uid, m.visibility, m.location, m.created_at,
				       m.like_count, m.comment_count
				FROM moments m
				WHERE m.deleted_at = 0
				  AND m.moment_id < $2
				  AND ($4 <= 0 OR m.uid = $4)
				  AND (
					m.visibility = 0
					OR m.uid = $1
					OR (
						m.visibility = 1
						AND (
							EXISTS (
								SELECT 1
								FROM friend f
								WHERE ((f.self_id = m.uid AND f.friend_id = $1)
									OR (f.self_id = $1 AND f.friend_id = m.uid))
							)
							OR EXISTS (
								SELECT 1
								FROM friend_apply fa
								WHERE fa.status = 1
								  AND ((fa.from_uid = m.uid AND fa.to_uid = $1)
									OR (fa.from_uid = $1 AND fa.to_uid = m.uid))
							)
						)
					)
				  )
				ORDER BY m.created_at DESC, m.moment_id DESC
				LIMIT $3
			)", viewer_uid, last_moment_id, limit + 1, author_uid);
		}

		if (static_cast<int>(rows.size()) > limit) {
			has_more = true;
		}

		for (size_t i = 0; i < rows.size() && static_cast<int>(moments.size()) < limit; ++i) {
			const auto& row = rows[i];
			MomentInfo info;
			info.moment_id = row["moment_id"].as<int64_t>();
			info.uid = row["uid"].as<int>();
			info.visibility = row["visibility"].as<int>();
			info.location = row["location"].is_null() ? "" : row["location"].c_str();
			info.created_at = row["created_at"].as<int64_t>();
			info.like_count = row["like_count"].as<int>();
			info.comment_count = row["comment_count"].as<int>();
			moments.push_back(info);
		}

		return true;
	}
	catch (const std::exception& e) {
		std::cerr << "GetMomentsFeed PostgreSQL exception: " << e.what() << std::endl;
		moments.clear();
		return false;
	}
}

bool PostgresDao::CanViewMoment(int viewer_uid, const MomentInfo& moment) {
	if (viewer_uid <= 0 || moment.uid <= 0) {
		return false;
	}
	if (viewer_uid == moment.uid) {
		return true;
	}
	if (moment.visibility == 0) {
		return true;
	}
	if (moment.visibility != 1) {
		return false;
	}

	auto con = pool_->getConnection();
	if (con == nullptr) {
		return false;
	}

	Defer defer([this, &con]() {
		pool_->returnConnection(std::move(con));
	});

	try {
		pqxx::read_transaction txn(*con->_con);
		const auto rows = txn.exec_params(
			"SELECT 1 "
			"WHERE EXISTS ("
			"    SELECT 1 FROM friend f "
			"    WHERE ((f.self_id = $1 AND f.friend_id = $2) OR (f.self_id = $2 AND f.friend_id = $1))"
			") "
			"OR EXISTS ("
			"    SELECT 1 FROM friend_apply fa "
			"    WHERE fa.status = 1 "
			"      AND ((fa.from_uid = $1 AND fa.to_uid = $2) OR (fa.from_uid = $2 AND fa.to_uid = $1))"
			")",
			viewer_uid,
			moment.uid);
		return !rows.empty();
	}
	catch (const std::exception& e) {
		std::cerr << "CanViewMoment PostgreSQL exception: " << e.what() << std::endl;
		return false;
	}
}

bool PostgresDao::GetMomentById(int64_t moment_id, MomentInfo& moment) {
	auto con = pool_->getConnection();
	if (con == nullptr) {
		return false;
	}

	Defer defer([this, &con]() {
		pool_->returnConnection(std::move(con));
	});

	try {
		pqxx::read_transaction txn(*con->_con);
		const auto rows = txn.exec_params(
			"SELECT moment_id, uid, visibility, location, created_at, deleted_at, like_count, comment_count "
			"FROM moments WHERE moment_id = $1 LIMIT 1",
			moment_id);
		if (rows.empty()) {
			return false;
		}

		const auto& row = rows[0];
		moment.moment_id = row["moment_id"].as<int64_t>();
		moment.uid = row["uid"].as<int>();
		moment.visibility = row["visibility"].as<int>();
		moment.location = row["location"].is_null() ? "" : row["location"].c_str();
		moment.created_at = row["created_at"].as<int64_t>();
		moment.deleted_at = row["deleted_at"].as<int64_t>();
		moment.like_count = row["like_count"].as<int>();
		moment.comment_count = row["comment_count"].as<int>();
		return true;
	}
	catch (const std::exception& e) {
		std::cerr << "GetMomentById PostgreSQL exception: " << e.what() << std::endl;
		return false;
	}
}

bool PostgresDao::DeleteMoment(int64_t moment_id, int uid) {
	auto con = pool_->getConnection();
	if (con == nullptr) {
		return false;
	}

	Defer defer([this, &con]() {
		pool_->returnConnection(std::move(con));
	});

	try {
		pqxx::work txn(*con->_con);
		auto now = std::chrono::duration_cast<std::chrono::seconds>(
			std::chrono::system_clock::now().time_since_epoch()).count();
		const auto rows = txn.exec_params(
			"UPDATE moments SET deleted_at = $1 WHERE moment_id = $2 AND uid = $3",
			now, moment_id, uid);
		txn.commit();
		return rows.affected_rows() > 0;
	}
	catch (const std::exception& e) {
		std::cerr << "DeleteMoment PostgreSQL exception: " << e.what() << std::endl;
		return false;
	}
}

bool PostgresDao::AddMomentLike(int64_t moment_id, int uid) {
	auto con = pool_->getConnection();
	if (con == nullptr) {
		return false;
	}

	Defer defer([this, &con]() {
		pool_->returnConnection(std::move(con));
	});

	try {
		pqxx::work txn(*con->_con);
		const auto inserted = txn.exec_params(
			"INSERT INTO moments_like(moment_id, uid, created_at) VALUES ($1, $2, $3) "
			"ON CONFLICT (moment_id, uid) DO NOTHING",
			moment_id, uid,
			static_cast<int64_t>(std::chrono::duration_cast<std::chrono::seconds>(
				std::chrono::system_clock::now().time_since_epoch()).count()));
		if (inserted.affected_rows() > 0) {
			txn.exec_params(
				"UPDATE moments SET like_count = like_count + 1 WHERE moment_id = $1",
				moment_id);
		}
		txn.commit();
		return true;
	}
	catch (const std::exception& e) {
		std::cerr << "AddMomentLike PostgreSQL exception: " << e.what() << std::endl;
		return false;
	}
}

bool PostgresDao::RemoveMomentLike(int64_t moment_id, int uid) {
	auto con = pool_->getConnection();
	if (con == nullptr) {
		return false;
	}

	Defer defer([this, &con]() {
		pool_->returnConnection(std::move(con));
	});

	try {
		pqxx::work txn(*con->_con);
		const auto deleted = txn.exec_params(
			"DELETE FROM moments_like WHERE moment_id = $1 AND uid = $2",
			moment_id, uid);
		if (deleted.affected_rows() > 0) {
			txn.exec_params(
				"UPDATE moments SET like_count = GREATEST(like_count - 1, 0) WHERE moment_id = $1",
				moment_id);
		}
		txn.commit();
		return true;
	}
	catch (const std::exception& e) {
		std::cerr << "RemoveMomentLike PostgreSQL exception: " << e.what() << std::endl;
		return false;
	}
}

bool PostgresDao::HasLikedMoment(int64_t moment_id, int uid) {
	auto con = pool_->getConnection();
	if (con == nullptr) {
		return false;
	}

	Defer defer([this, &con]() {
		pool_->returnConnection(std::move(con));
	});

	try {
		pqxx::read_transaction txn(*con->_con);
		const auto rows = txn.exec_params(
			"SELECT 1 FROM moments_like WHERE moment_id = $1 AND uid = $2 LIMIT 1",
			moment_id, uid);
		return !rows.empty();
	}
	catch (const std::exception& e) {
		std::cerr << "HasLikedMoment PostgreSQL exception: " << e.what() << std::endl;
		return false;
	}
}

bool PostgresDao::GetMomentLikes(int64_t moment_id, int limit,
	std::vector<MomentLikeInfo>& likes, bool& has_more) {
	likes.clear();
	has_more = false;
	if (limit <= 0) {
		limit = 20;
	}

	auto con = pool_->getConnection();
	if (con == nullptr) {
		return false;
	}

	Defer defer([this, &con]() {
		pool_->returnConnection(std::move(con));
	});

	try {
		pqxx::read_transaction txn(*con->_con);
		const auto rows = txn.exec_params(
			"SELECT ml.id, ml.moment_id, ml.uid, ml.created_at, "
			"       COALESCE(u.nick, '') AS user_nick, COALESCE(u.icon, '') AS user_icon "
			"FROM moments_like ml "
			"LEFT JOIN \"user\" u ON ml.uid = u.uid "
			"WHERE ml.moment_id = $1 ORDER BY ml.created_at DESC LIMIT $2",
			moment_id, limit + 1);

		if (static_cast<int>(rows.size()) > limit) {
			has_more = true;
		}

		for (size_t i = 0; i < rows.size() && static_cast<int>(likes.size()) < limit; ++i) {
			const auto& row = rows[i];
			MomentLikeInfo info;
			info.id = row["id"].as<int64_t>();
			info.moment_id = row["moment_id"].as<int64_t>();
			info.uid = row["uid"].as<int>();
			info.user_nick = row["user_nick"].is_null() ? "" : row["user_nick"].c_str();
			info.user_icon = row["user_icon"].is_null() ? "" : row["user_icon"].c_str();
			info.created_at = row["created_at"].as<int64_t>();
			likes.push_back(info);
		}

		return true;
	}
	catch (const std::exception& e) {
		std::cerr << "GetMomentLikes PostgreSQL exception: " << e.what() << std::endl;
		return false;
	}
}

bool PostgresDao::AddMomentComment(const MomentCommentInfo& comment) {
	auto con = pool_->getConnection();
	if (con == nullptr) {
		return false;
	}

	Defer defer([this, &con]() {
		pool_->returnConnection(std::move(con));
	});

	try {
		pqxx::work txn(*con->_con);
		txn.exec_params(
			"INSERT INTO moments_comment(moment_id, uid, content, reply_uid, created_at) "
			"VALUES ($1, $2, $3, $4, $5)",
			comment.moment_id,
			comment.uid,
			comment.content,
			comment.reply_uid,
			comment.created_at);
		txn.exec_params(
			"UPDATE moments SET comment_count = comment_count + 1 WHERE moment_id = $1",
			comment.moment_id);
		txn.commit();
		return true;
	}
	catch (const std::exception& e) {
		std::cerr << "AddMomentComment PostgreSQL exception: " << e.what() << std::endl;
		return false;
	}
}

bool PostgresDao::DeleteMomentComment(int64_t comment_id, int uid) {
	auto con = pool_->getConnection();
	if (con == nullptr) {
		return false;
	}

	Defer defer([this, &con]() {
		pool_->returnConnection(std::move(con));
	});

	try {
		pqxx::work txn(*con->_con);
		auto now = std::chrono::duration_cast<std::chrono::seconds>(
			std::chrono::system_clock::now().time_since_epoch()).count();
		const auto rows = txn.exec_params(
			"UPDATE moments_comment mc SET deleted_at = $1 "
			"WHERE mc.id = $2 AND mc.deleted_at = 0 "
			"AND (mc.uid = $3 OR EXISTS ("
			"    SELECT 1 FROM moments m WHERE m.moment_id = mc.moment_id AND m.uid = $3 AND m.deleted_at = 0"
			"))",
			now, comment_id, uid);
		if (rows.affected_rows() > 0) {
			txn.exec_params(
				"DELETE FROM moments_comment_like WHERE comment_id = $1",
				comment_id);
			txn.exec_params(
				"UPDATE moments SET comment_count = GREATEST(comment_count - 1, 0) "
				"WHERE moment_id = (SELECT moment_id FROM moments_comment WHERE id = $1)",
				comment_id);
		}
		txn.commit();
		return rows.affected_rows() > 0;
	}
	catch (const std::exception& e) {
		std::cerr << "DeleteMomentComment PostgreSQL exception: " << e.what() << std::endl;
		return false;
	}
}

bool PostgresDao::GetMomentComments(int64_t moment_id, int64_t last_comment_id, int limit,
	std::vector<MomentCommentInfo>& comments, bool& has_more) {
	comments.clear();
	has_more = false;
	if (limit <= 0) {
		limit = 20;
	}

	auto con = pool_->getConnection();
	if (con == nullptr) {
		return false;
	}

	Defer defer([this, &con]() {
		pool_->returnConnection(std::move(con));
	});

	try {
		pqxx::read_transaction txn(*con->_con);
		pqxx::result rows;
		if (last_comment_id <= 0) {
			rows = txn.exec_params(
				"SELECT mc.id, mc.moment_id, mc.uid, mc.content, mc.reply_uid, mc.created_at, mc.deleted_at, "
				"       COALESCE(u.nick, '') AS user_nick, COALESCE(u.icon, '') AS user_icon, "
				"       COALESCE(ru.nick, '') AS reply_nick "
				"FROM moments_comment mc "
				"LEFT JOIN \"user\" u ON mc.uid = u.uid "
				"LEFT JOIN \"user\" ru ON mc.reply_uid = ru.uid "
				"WHERE mc.moment_id = $1 AND mc.deleted_at = 0 "
				"ORDER BY mc.created_at ASC LIMIT $2",
				moment_id, limit + 1);
		}
		else {
			rows = txn.exec_params(
				"SELECT mc.id, mc.moment_id, mc.uid, mc.content, mc.reply_uid, mc.created_at, mc.deleted_at, "
				"       COALESCE(u.nick, '') AS user_nick, COALESCE(u.icon, '') AS user_icon, "
				"       COALESCE(ru.nick, '') AS reply_nick "
				"FROM moments_comment mc "
				"LEFT JOIN \"user\" u ON mc.uid = u.uid "
				"LEFT JOIN \"user\" ru ON mc.reply_uid = ru.uid "
				"WHERE mc.moment_id = $1 AND mc.deleted_at = 0 AND mc.id > $2 "
				"ORDER BY mc.created_at ASC LIMIT $3",
				moment_id, last_comment_id, limit + 1);
		}

		if (static_cast<int>(rows.size()) > limit) {
			has_more = true;
		}

		for (size_t i = 0; i < rows.size() && static_cast<int>(comments.size()) < limit; ++i) {
			const auto& row = rows[i];
			MomentCommentInfo info;
			info.id = row["id"].as<int64_t>();
			info.moment_id = row["moment_id"].as<int64_t>();
			info.uid = row["uid"].as<int>();
			info.content = row["content"].is_null() ? "" : row["content"].c_str();
			info.reply_uid = row["reply_uid"].as<int>();
			info.user_nick = row["user_nick"].is_null() ? "" : row["user_nick"].c_str();
			info.user_icon = row["user_icon"].is_null() ? "" : row["user_icon"].c_str();
			info.reply_nick = row["reply_nick"].is_null() ? "" : row["reply_nick"].c_str();
			info.created_at = row["created_at"].as<int64_t>();
			info.deleted_at = row["deleted_at"].as<int64_t>();
			comments.push_back(info);
		}

		return true;
	}
	catch (const std::exception& e) {
		std::cerr << "GetMomentComments PostgreSQL exception: " << e.what() << std::endl;
		return false;
	}
}

bool PostgresDao::AddMomentCommentLike(int64_t comment_id, int uid) {
	auto con = pool_->getConnection();
	if (con == nullptr) {
		return false;
	}

	Defer defer([this, &con]() {
		pool_->returnConnection(std::move(con));
	});

	try {
		pqxx::work txn(*con->_con);
		txn.exec_params(
			"INSERT INTO moments_comment_like(comment_id, uid, created_at) "
			"SELECT $1, $2, $3 "
			"WHERE EXISTS (SELECT 1 FROM moments_comment WHERE id = $1 AND deleted_at = 0) "
			"ON CONFLICT (comment_id, uid) DO NOTHING",
			comment_id,
			uid,
			static_cast<int64_t>(std::chrono::duration_cast<std::chrono::seconds>(
				std::chrono::system_clock::now().time_since_epoch()).count()));
		txn.commit();
		return true;
	}
	catch (const std::exception& e) {
		std::cerr << "AddMomentCommentLike PostgreSQL exception: " << e.what() << std::endl;
		return false;
	}
}

bool PostgresDao::RemoveMomentCommentLike(int64_t comment_id, int uid) {
	auto con = pool_->getConnection();
	if (con == nullptr) {
		return false;
	}

	Defer defer([this, &con]() {
		pool_->returnConnection(std::move(con));
	});

	try {
		pqxx::work txn(*con->_con);
		txn.exec_params(
			"DELETE FROM moments_comment_like WHERE comment_id = $1 AND uid = $2",
			comment_id,
			uid);
		txn.commit();
		return true;
	}
	catch (const std::exception& e) {
		std::cerr << "RemoveMomentCommentLike PostgreSQL exception: " << e.what() << std::endl;
		return false;
	}
}

bool PostgresDao::HasLikedMomentComment(int64_t comment_id, int uid) {
	auto con = pool_->getConnection();
	if (con == nullptr) {
		return false;
	}

	Defer defer([this, &con]() {
		pool_->returnConnection(std::move(con));
	});

	try {
		pqxx::read_transaction txn(*con->_con);
		const auto rows = txn.exec_params(
			"SELECT 1 FROM moments_comment_like WHERE comment_id = $1 AND uid = $2 LIMIT 1",
			comment_id,
			uid);
		return !rows.empty();
	}
	catch (const std::exception& e) {
		std::cerr << "HasLikedMomentComment PostgreSQL exception: " << e.what() << std::endl;
		return false;
	}
}

bool PostgresDao::GetMomentCommentLikes(int64_t comment_id, int limit,
	std::vector<MomentLikeInfo>& likes, bool& has_more) {
	likes.clear();
	has_more = false;
	if (limit <= 0) {
		limit = 20;
	}

	auto con = pool_->getConnection();
	if (con == nullptr) {
		return false;
	}

	Defer defer([this, &con]() {
		pool_->returnConnection(std::move(con));
	});

	try {
		pqxx::read_transaction txn(*con->_con);
		const auto rows = txn.exec_params(
			"SELECT mcl.id, mcl.comment_id, mcl.uid, mcl.created_at, "
			"       COALESCE(u.nick, '') AS user_nick, COALESCE(u.icon, '') AS user_icon "
			"FROM moments_comment_like mcl "
			"LEFT JOIN \"user\" u ON mcl.uid = u.uid "
			"WHERE mcl.comment_id = $1 ORDER BY mcl.created_at DESC LIMIT $2",
			comment_id, limit + 1);

		if (static_cast<int>(rows.size()) > limit) {
			has_more = true;
		}

		for (size_t i = 0; i < rows.size() && static_cast<int>(likes.size()) < limit; ++i) {
			const auto& row = rows[i];
			MomentLikeInfo info;
			info.id = row["id"].as<int64_t>();
			info.moment_id = row["comment_id"].as<int64_t>();
			info.uid = row["uid"].as<int>();
			info.user_nick = row["user_nick"].is_null() ? "" : row["user_nick"].c_str();
			info.user_icon = row["user_icon"].is_null() ? "" : row["user_icon"].c_str();
			info.created_at = row["created_at"].as<int64_t>();
			likes.push_back(info);
		}

		return true;
	}
	catch (const std::exception& e) {
		std::cerr << "GetMomentCommentLikes PostgreSQL exception: " << e.what() << std::endl;
		return false;
	}
}

