set(MEMOCHAT_QML_APP_SOURCES
    app/bootstrap/main.cpp
    app/bootstrap/MainLogging.cpp
    app/bootstrap/MainPlatformBootstrap.cpp
    app/bootstrap/MainQmlTypeRegistry.cpp
    app/bootstrap/MainQmlEngineSetup.cpp
    app/bootstrap/MainQmlWindowLoader.cpp
    app/bootstrap/MainRuntimeConfig.cpp
    app/composition/AppFeatureRegistry.cpp
    app/composition/AppComposition.cpp
    app/composition/AppPortRegistry.cpp
    app/composition/AppPortBinder.cpp
    app/composition/AppSessionPortBinder.cpp
    app/composition/AppSessionAuthPortBinder.cpp
    app/composition/AppPostLoginBootstrapPortBinder.cpp
    app/composition/AppRelationBootstrapPortBinder.cpp
    app/composition/AppRegisterCountdownPortBinder.cpp
    app/composition/AppSessionLogoutPortBinder.cpp
    app/composition/AppMediaPortBinder.cpp
    app/composition/AppCallPortBinder.cpp
    app/composition/AppFeaturePortBinder.cpp
    app/composition/AppAuthFeaturePortBinder.cpp
    app/composition/AppContactFeaturePortBinder.cpp
    app/composition/AppGroupFeaturePortBinder.cpp
    app/composition/AppProfileFeaturePortBinder.cpp
    app/composition/AppConnectionPortBinder.cpp
    app/composition/AppSignalBinder.cpp
    app/composition/AppHttpSignalBinder.cpp
    app/composition/AppChatTransportSignalBinder.cpp
    app/composition/AppChatDispatcherSignalBinder.cpp
    app/composition/AppChatDispatcherSignalRoutes.cpp
    app/composition/AppChatDispatcherRouterFactory.cpp
    app/composition/AppCallSignalBinder.cpp
    app/composition/AppShellSignalBinder.cpp
    app/composition/AppTimerSignalBinder.cpp
    app/events/AppChatDispatcherEventRouter.cpp
    app/events/AppHttpEventRouter.cpp
    app/shell/AppShellStateController.cpp
    app/shell/ShellViewModel.cpp
    app/window/MainWindowEffects.cpp
    app/window/MainWindowHooks.cpp
    app/controller/AppController.cpp
    app/controller/AppControllerChatFeatureBinding.cpp
    app/controller/AppChatProjectionBinding.cpp
    app/controller/AppChatSendBinding.cpp
    app/controller/AppChatDialogBinding.cpp
    app/controller/AppChatHistoryBinding.cpp
    app/controller/AppChatGroupBinding.cpp
    app/controller/AppChatMediaBinding.cpp
    app/controller/AppChatReadMutationBinding.cpp
    app/controller/ChatEventDependenciesFactory.cpp
    app/controller/ChatDialogSelectionPortFactory.cpp
    app/controller/ContactEventDependenciesFactory.cpp
    app/controller/GroupManagementEffectPortFactory.cpp
    app/controller/IncomingMessageRouterFactory.cpp
    app/controller/PrivateHistoryDependenciesFactory.cpp
    app/session/AppSessionCoordinator.cpp
    app/session/AppSessionCoordinatorAuthTimers.cpp
    app/session/AppSessionCoordinatorConnectionState.cpp
    app/session/AppSessionCoordinatorLogout.cpp
    app/session/SessionAuthCoordinator.cpp
    app/session/SessionAuthCoordinatorCommands.cpp
    app/session/SessionAuthCoordinatorLoginResponse.cpp
    app/session/SessionAuthCoordinatorAuthResponses.cpp
    app/session/SessionChatEntryCoordinator.cpp
    app/session/SessionRelationBootstrap.cpp
    app/coordinators/RegisterCountdownController.cpp
    app/coordinators/CallCoordinator.cpp
    app/coordinators/CallCoordinatorCommands.cpp
    app/coordinators/CallCoordinatorEvents.cpp
    app/coordinators/CallCoordinatorHttp.cpp
    app/coordinators/CallCoordinatorLivekit.cpp
    app/coordinators/CallCoordinatorPayloadPolicy.cpp
    app/connection/AppChatConnectionCoordinator.cpp
    app/connection/AppChatConnectionPolicy.cpp
    app/controller/AppControllerContactEvents.cpp
    app/controller/AppControllerDialogListPorts.cpp
    app/controller/AppControllerDialogState.cpp
    app/coordinators/MediaCoordinator.cpp
    app/coordinators/MediaPendingAttachmentRunner.cpp
    app/controller/AppControllerGroupCommands.cpp
    app/controller/AppControllerModels.cpp
    app/controller/AppControllerDialogModels.cpp
    app/controller/AppControllerPrivateHistory.cpp
    app/controller/AppControllerPrivateSelection.cpp
    app/controller/AppControllerGroupSelection.cpp
    app/controller/AppControllerDialogSelection.cpp
    app/controller/AppControllerPagination.cpp
    app/controller/AppControllerNavigation.cpp
    app/controller/AppControllerUiProperties.cpp
    app/controller/AppControllerUserProperties.cpp
    app/controller/AppControllerGroupProperties.cpp
    app/controller/AppControllerModelProperties.cpp
    app/controller/AppControllerContactState.cpp
    app/controller/AppControllerStatusState.cpp
    app/controller/AppControllerLoadingState.cpp
    app/controller/AppControllerDialogRuntimeState.cpp
    app/controller/AppControllerIncomingBuffer.cpp
    app/controller/AppControllerProfileState.cpp
    app/controller/AppControllerBootstrapState.cpp
    app/controller/AppControllerGroupEvents.cpp
    app/controller/AppControllerGroupResponses.cpp
    app/controller/AppControllerGroupResponseErrors.cpp
    app/controller/AppControllerGroupManagementResponses.cpp
    app/controller/AppControllerGroupHistoryResponses.cpp
    app/controller/AppControllerGroupMessageResponses.cpp
    app/controller/AppControllerPrivateMessageResponses.cpp
    app/controller/AppControllerDialogMetaResponses.cpp
    app/controller/AppControllerPendingAttachments.cpp
    app/controller/AppControllerMediaUploadQueue.cpp
    app/controller/AppControllerMessageDispatch.cpp
    app/controller/AppControllerPrivateEvents.cpp
    app/connection/AppControllerChatBootstrap.cpp
    app/controller/AppControllerRelationBootstrap.cpp
)

set(MEMOCHAT_QML_APP_HEADERS
    app/bootstrap/MainLogging.h
    app/bootstrap/MainPlatformBootstrap.h
    app/bootstrap/MainQmlBootstrap.h
    app/bootstrap/MainRuntimeConfig.h
    app/composition/AppFeatureRegistry.h
    app/composition/AppComposition.h
    app/composition/AppPortRegistry.h
    app/composition/AppChatDispatcherRouterFactory.h
    app/composition/AppChatDispatcherSignalRoutes.h
    app/composition/AppPortBinder.h
    app/composition/AppSignalBinder.h
    app/events/AppChatDispatcherEventRouter.h
    app/events/AppChatDispatcherGroupResponseHandlers.h
    app/events/AppHttpEventRouter.h
    app/shell/AppShellStateController.h
    app/shell/ShellViewModel.h
    app/window/MainWindowEffects.h
    app/window/MainWindowHooks.h
    app/controller/AppController.h
    app/connection/AppControllerConnectionState.h
    app/connection/AppChatConnectionCoordinator.h
    app/connection/AppChatConnectionPolicy.h
    app/coordinators/CallCoordinatorPayloadPolicy.h
    app/coordinators/MediaPendingAttachmentRunner.h
    app/controller/AppControllerRuntimeState.h
    app/controller/AppControllerUserState.h
    app/controller/ChatEventDependenciesFactory.h
    app/controller/ChatDialogSelectionPortFactory.h
    app/controller/ContactEventDependenciesFactory.h
    app/controller/GroupManagementEffectPortFactory.h
    app/controller/IncomingMessageRouterFactory.h
    app/controller/PrivateHistoryDependenciesFactory.h
    app/coordinators/AppCoordinators.h
)
