set(MEMOCHAT_QML_APP_SOURCES
    app/bootstrap/main.cpp
    app/bootstrap/MainLogging.cpp
    app/bootstrap/MainPlatformBootstrap.cpp
    app/bootstrap/MainQmlTypeRegistry.cpp
    app/bootstrap/MainQmlEngineSetup.cpp
    app/bootstrap/MainQmlWindowLoader.cpp
    app/bootstrap/MainRuntimeConfig.cpp
    app/shell/ShellViewModel.cpp
    app/window/MainWindowEffects.cpp
    app/window/MainWindowHooks.cpp
    app/controller/AppController.cpp
    app/session/AppSessionCoordinator.cpp
    app/session/SessionAuthCoordinator.cpp
    app/session/SessionAuthCoordinatorCommands.cpp
    app/session/SessionAuthCoordinatorLoginResponse.cpp
    app/session/SessionAuthCoordinatorAuthResponses.cpp
    app/session/SessionChatEntryCoordinator.cpp
    app/session/SessionRelationBootstrap.cpp
    app/coordinators/RegisterCountdownController.cpp
    app/controller/AppControllerAuth.cpp
    app/controller/AppControllerAuthResponses.cpp
    app/coordinators/CallCoordinator.cpp
    app/coordinators/CallCoordinatorPayloadPolicy.cpp
    app/connection/AppChatConnectionCoordinator.cpp
    app/connection/AppChatConnectionPolicy.cpp
    app/coordinators/ContactCoordinatorShell.cpp
    app/controller/AppControllerContactEvents.cpp
    app/controller/AppControllerDialogListEvents.cpp
    app/controller/AppControllerDialogState.cpp
    app/controller/AppControllerDialogCommands.cpp
    app/coordinators/GroupCoordinator.cpp
    app/coordinators/MediaCoordinator.cpp
    app/coordinators/ProfileCoordinator.cpp
    app/controller/AppControllerGroupCommands.cpp
    app/controller/AppControllerGroupPayloads.cpp
    app/controller/AppControllerGroupManagement.cpp
    app/controller/AppControllerModels.cpp
    app/controller/AppControllerDialogModels.cpp
    app/controller/AppControllerPrivateHistory.cpp
    app/controller/AppControllerReadAcks.cpp
    app/controller/AppControllerPrivateSelection.cpp
    app/controller/AppControllerContactSelection.cpp
    app/controller/AppControllerGroupSelection.cpp
    app/controller/AppControllerDialogSelection.cpp
    app/controller/AppControllerPagination.cpp
    app/controller/AppControllerNavigation.cpp
    app/controller/AppControllerUiProperties.cpp
    app/controller/AppControllerUserProperties.cpp
    app/controller/AppControllerGroupProperties.cpp
    app/controller/AppControllerModelProperties.cpp
    app/controller/AppControllerContactState.cpp
    app/controller/AppControllerStatusState.cpp
    app/controller/AppControllerLoadingState.cpp
    app/controller/AppControllerDialogRuntimeState.cpp
    app/controller/AppControllerProfileState.cpp
    app/controller/AppControllerBootstrapState.cpp
    app/controller/AppControllerProfileCommands.cpp
    app/controller/AppControllerGroupEvents.cpp
    app/controller/AppControllerGroupResponses.cpp
    app/controller/AppControllerGroupResponseErrors.cpp
    app/controller/AppControllerGroupManagementResponses.cpp
    app/controller/AppControllerGroupHistoryResponses.cpp
    app/controller/AppControllerGroupMessageResponses.cpp
    app/controller/AppControllerPrivateMessageResponses.cpp
    app/controller/AppControllerDialogMetaResponses.cpp
    app/controller/AppControllerMedia.cpp
    app/controller/AppControllerPendingAttachments.cpp
    app/controller/AppControllerMediaUploadQueue.cpp
    app/controller/AppControllerMessageDispatch.cpp
    app/controller/AppControllerPrivateEvents.cpp
    app/controller/AppControllerMessageStatus.cpp
    app/controller/AppControllerPrivateHistoryResponses.cpp
    app/controller/AppControllerPrivateMessageEvents.cpp
    app/controller/AppControllerPrivateReadEvents.cpp
    app/connection/AppControllerChatBootstrap.cpp
    app/controller/AppControllerRelationBootstrap.cpp
)

set(MEMOCHAT_QML_APP_HEADERS
    app/bootstrap/MainLogging.h
    app/bootstrap/MainPlatformBootstrap.h
    app/bootstrap/MainQmlBootstrap.h
    app/bootstrap/MainRuntimeConfig.h
    app/shell/ShellViewModel.h
    app/window/MainWindowEffects.h
    app/window/MainWindowHooks.h
    app/controller/AppController.h
    app/connection/AppControllerConnectionState.h
    app/connection/AppChatConnectionPolicy.h
    app/coordinators/CallCoordinatorPayloadPolicy.h
    app/controller/AppControllerDialogStateData.h
    app/controller/AppControllerGroupState.h
    app/controller/AppControllerGroupPayloads.h
    app/controller/AppControllerPendingSendState.h
    app/controller/AppControllerRuntimeState.h
    app/controller/AppControllerUserState.h
    app/coordinators/AppCoordinators.h
)
