CREATE SCHEMA IF NOT EXISTS "__APP_SCHEMA__";
SET search_path TO "__APP_SCHEMA__", public;

-- ============================================
-- 朋友圈 (Moments) Tables
-- ============================================

-- 朋友圈索引表
CREATE TABLE IF NOT EXISTS moments (
    moment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid integer NOT NULL DEFAULT 0,
    visibility smallint NOT NULL DEFAULT 0,
    location varchar(128) NOT NULL DEFAULT '',
    created_at bigint NOT NULL DEFAULT 0,
    deleted_at bigint NOT NULL DEFAULT 0,
    like_count integer NOT NULL DEFAULT 0,
    comment_count integer NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_moments_uid_created ON moments(uid, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_moments_deleted_at ON moments(deleted_at);

-- 朋友圈点赞表
CREATE TABLE IF NOT EXISTS moments_like (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    moment_id bigint NOT NULL,
    uid integer NOT NULL,
    created_at bigint NOT NULL DEFAULT 0,
    CONSTRAINT uq_moments_like UNIQUE (moment_id, uid)
);
CREATE INDEX IF NOT EXISTS idx_moments_like_moment_id ON moments_like(moment_id);
CREATE INDEX IF NOT EXISTS idx_moments_like_uid ON moments_like(uid);

-- 朋友圈评论表
CREATE TABLE IF NOT EXISTS moments_comment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    moment_id bigint NOT NULL,
    uid integer NOT NULL,
    content text NOT NULL DEFAULT '',
    reply_uid integer NOT NULL DEFAULT 0,
    created_at bigint NOT NULL DEFAULT 0,
    deleted_at bigint NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_moments_comment_moment_created ON moments_comment(moment_id, created_at ASC);
CREATE INDEX IF NOT EXISTS idx_moments_comment_uid ON moments_comment(uid);

-- 朋友圈评论点赞表
CREATE TABLE IF NOT EXISTS moments_comment_like (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id bigint NOT NULL,
    uid integer NOT NULL,
    created_at bigint NOT NULL DEFAULT 0,
    CONSTRAINT uq_moments_comment_like UNIQUE (comment_id, uid)
);
CREATE INDEX IF NOT EXISTS idx_moments_comment_like_comment_id ON moments_comment_like(comment_id);
CREATE INDEX IF NOT EXISTS idx_moments_comment_like_uid ON moments_comment_like(uid);
