-- gateserver split Phase 2 (slice 2a): memo_moments database schema.
-- Loaded into the memo_moments database. Owns the moments feed relational data
-- (Mongo holds moment *content*; author nick/avatar come via Redis ubaseinfo_
-- cache / AccountService API, NOT a cross-DB JOIN). Mirrors the memo.moments*
-- DDL so migrated data fits exactly.

CREATE SCHEMA IF NOT EXISTS memo;

CREATE TABLE IF NOT EXISTS memo.moments (
    moment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid integer DEFAULT 0 NOT NULL,
    visibility smallint DEFAULT 0 NOT NULL,
    location character varying(128) DEFAULT ''::character varying NOT NULL,
    created_at bigint DEFAULT 0 NOT NULL,
    deleted_at bigint DEFAULT 0 NOT NULL,
    like_count integer DEFAULT 0 NOT NULL,
    comment_count integer DEFAULT 0 NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_moments_deleted_at ON memo.moments USING btree (deleted_at);
CREATE INDEX IF NOT EXISTS idx_moments_uid_created ON memo.moments USING btree (uid, created_at DESC);

CREATE TABLE IF NOT EXISTS memo.moments_comment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    moment_id bigint NOT NULL,
    uid integer NOT NULL,
    content text DEFAULT ''::text NOT NULL,
    reply_uid integer DEFAULT 0 NOT NULL,
    created_at bigint DEFAULT 0 NOT NULL,
    deleted_at bigint DEFAULT 0 NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_moments_comment_moment_created
    ON memo.moments_comment USING btree (moment_id, created_at);
CREATE INDEX IF NOT EXISTS idx_moments_comment_uid ON memo.moments_comment USING btree (uid);

CREATE TABLE IF NOT EXISTS memo.moments_comment_like (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id bigint NOT NULL,
    uid integer NOT NULL,
    created_at bigint DEFAULT 0 NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_moments_comment_like_comment
    ON memo.moments_comment_like USING btree (comment_id);

CREATE TABLE IF NOT EXISTS memo.moments_like (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    moment_id bigint NOT NULL,
    uid integer NOT NULL,
    created_at bigint DEFAULT 0 NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_moments_like_moment ON memo.moments_like USING btree (moment_id);

GRANT USAGE ON SCHEMA memo TO memo_moments_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA memo TO memo_moments_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA memo TO memo_moments_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA memo GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO memo_moments_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA memo GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO memo_moments_app;
