-- gateserver split Phase 2 (slice 2a): memo_media database schema.
-- Loaded into the memo_media database by migrate_phase2_db_split.sh. Owns the
-- media asset metadata only (objects live in MinIO). Mirrors the original
-- memo.chat_media_asset DDL so data migrated from memo_pg fits exactly.

CREATE SCHEMA IF NOT EXISTS memo;

CREATE TABLE IF NOT EXISTS memo.chat_media_asset (
    media_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_key character varying(64) NOT NULL,
    owner_uid integer NOT NULL,
    media_type character varying(16) NOT NULL,
    origin_file_name character varying(255) NOT NULL,
    mime character varying(127) DEFAULT ''::character varying NOT NULL,
    size_bytes bigint DEFAULT 0 NOT NULL,
    storage_provider character varying(32) DEFAULT 'local'::character varying NOT NULL,
    storage_path character varying(1024) NOT NULL,
    created_at_ms bigint NOT NULL,
    deleted_at_ms bigint DEFAULT 0 NOT NULL,
    status smallint DEFAULT 1 NOT NULL,
    CONSTRAINT uq_chat_media_asset_key UNIQUE (media_key)
);
CREATE INDEX IF NOT EXISTS idx_chat_media_asset_owner_created
    ON memo.chat_media_asset USING btree (owner_uid, created_at_ms);

CREATE TABLE IF NOT EXISTS memo.chat_media_access_grant (
    grant_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_id bigint NOT NULL,
    grantee_uid integer NOT NULL,
    grant_scope character varying(32) DEFAULT 'direct'::character varying NOT NULL,
    created_at_ms bigint NOT NULL,
    revoked_at_ms bigint DEFAULT 0 NOT NULL,
    CONSTRAINT uq_chat_media_access_grant UNIQUE (media_id, grantee_uid, grant_scope),
    CONSTRAINT fk_chat_media_access_grant_media
        FOREIGN KEY (media_id) REFERENCES memo.chat_media_asset(media_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_chat_media_access_grant_grantee
    ON memo.chat_media_access_grant USING btree (grantee_uid, media_id)
    WHERE revoked_at_ms = 0;

-- Least-privilege grants for the service role.
GRANT USAGE ON SCHEMA memo TO memo_media_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA memo TO memo_media_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA memo TO memo_media_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA memo GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO memo_media_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA memo GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO memo_media_app;
