-- gateserver split Phase 2 (slice 2b): memo_account database schema.
-- Loaded into the memo_account database. Owns the user identity aggregate
-- (user + user_id sequence helper). ChatServer + Register/Login/Account services
-- reach this via [AccountPostgres]; their friend/group/message/chat queries stay
-- on the main [Postgres] db. Cross-DB JOINs were removed first (the user JOINs in
-- friend/group/message DAO queries now use a batch GetUsersByUids resolver).
-- Mirrors the original memo."user" / memo.user_id DDL so migrated data fits.

CREATE SCHEMA IF NOT EXISTS memo;

CREATE TABLE IF NOT EXISTS memo."user" (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid integer DEFAULT 0 NOT NULL,
    name character varying(255) DEFAULT ''::character varying NOT NULL,
    email character varying(255) DEFAULT ''::character varying NOT NULL,
    pwd character varying(255) DEFAULT ''::character varying NOT NULL,
    nick character varying(255) DEFAULT ''::character varying NOT NULL,
    "desc" character varying(255) DEFAULT ''::character varying NOT NULL,
    sex integer DEFAULT 0 NOT NULL,
    icon character varying(255) DEFAULT ''::character varying NOT NULL,
    user_id character varying(10),
    CONSTRAINT uq_user_email UNIQUE (email),
    CONSTRAINT uq_user_uid UNIQUE (uid),
    CONSTRAINT uq_user_user_id UNIQUE (user_id)
);
CREATE INDEX IF NOT EXISTS idx_user_name ON memo."user" USING btree (name);

CREATE TABLE IF NOT EXISTS memo.user_id (
    id integer NOT NULL PRIMARY KEY
);

GRANT USAGE ON SCHEMA memo TO memo_account_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA memo TO memo_account_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA memo TO memo_account_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA memo GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO memo_account_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA memo GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO memo_account_app;
