-- gateserver split Phase 2 (slice 2b): memo_account database schema.
-- Loaded into the memo_account database. Owns the user identity aggregate
-- (user + user_id sequence helper). ChatServer + Register/Login/Account services
-- reach this via [AccountPostgres]; their friend/group/message/chat queries stay
-- on the main [Postgres] db. Cross-DB JOINs were removed first (the user JOINs in
-- friend/group/message DAO queries now use a batch GetUsersByUids resolver).
-- Mirrors the original memo."user" / memo.user_id DDL so migrated data fits.

CREATE SCHEMA IF NOT EXISTS memo;

CREATE TABLE IF NOT EXISTS memo."user" (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid integer DEFAULT 0 NOT NULL,
    name character varying(255) DEFAULT ''::character varying NOT NULL,
    email character varying(255) DEFAULT ''::character varying NOT NULL,
    pwd character varying(255) DEFAULT ''::character varying NOT NULL,
    password_hash text DEFAULT ''::text NOT NULL,
    nick character varying(255) DEFAULT ''::character varying NOT NULL,
    "desc" character varying(255) DEFAULT ''::character varying NOT NULL,
    sex integer DEFAULT 0 NOT NULL,
    icon character varying(255) DEFAULT ''::character varying NOT NULL,
    user_id character varying(10),
    adult_attested_at_ms bigint DEFAULT 0 NOT NULL,
    r18_access_state smallint DEFAULT 0 NOT NULL,
    CONSTRAINT uq_user_email UNIQUE (email),
    CONSTRAINT uq_user_uid UNIQUE (uid),
    CONSTRAINT uq_user_user_id UNIQUE (user_id),
    CONSTRAINT ck_user_r18_access_state CHECK (r18_access_state IN (0, 1, 2)),
    CONSTRAINT ck_user_adult_attested_at_ms CHECK (adult_attested_at_ms >= 0)
);
CREATE INDEX IF NOT EXISTS idx_user_name ON memo."user" USING btree (name);

CREATE TABLE IF NOT EXISTS memo.user_id (
    id integer NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS memo.auth_refresh_token (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid integer NOT NULL,
    selector text NOT NULL,
    verifier_hash text NOT NULL,
    issued_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at timestamptz NOT NULL,
    rotated_at timestamptz,
    revoked_at timestamptz,
    replaced_by_selector text,
    user_agent text NOT NULL DEFAULT '',
    ip_hash text NOT NULL DEFAULT '',
    CONSTRAINT uq_auth_refresh_token_selector UNIQUE (selector),
    CONSTRAINT fk_auth_refresh_token_uid FOREIGN KEY (uid) REFERENCES memo."user"(uid) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_auth_refresh_token_uid_active
    ON memo.auth_refresh_token(uid) WHERE revoked_at IS NULL AND rotated_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_auth_refresh_token_expires_at ON memo.auth_refresh_token(expires_at);

GRANT USAGE ON SCHEMA memo TO memo_account_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA memo TO memo_account_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA memo TO memo_account_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA memo GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO memo_account_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA memo GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO memo_account_app;
