CREATE SCHEMA IF NOT EXISTS memo;

CREATE TABLE IF NOT EXISTS memo.auth_refresh_token (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid integer NOT NULL,
    selector text NOT NULL,
    verifier_hash text NOT NULL,
    issued_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at timestamptz NOT NULL,
    rotated_at timestamptz,
    revoked_at timestamptz,
    replaced_by_selector text,
    user_agent text NOT NULL DEFAULT '',
    ip_hash text NOT NULL DEFAULT '',
    CONSTRAINT uq_auth_refresh_token_selector UNIQUE (selector),
    CONSTRAINT fk_auth_refresh_token_uid FOREIGN KEY (uid) REFERENCES memo."user"(uid) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_auth_refresh_token_uid_active
    ON memo.auth_refresh_token(uid) WHERE revoked_at IS NULL AND rotated_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_auth_refresh_token_expires_at ON memo.auth_refresh_token(expires_at);

GRANT USAGE ON SCHEMA memo TO memo_account_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA memo TO memo_account_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA memo TO memo_account_app;
