-- Add explicit media download grants so media_key is no longer an access capability.
-- Owner reads remain implicit through chat_media_asset.owner_uid; cross-owner reads
-- require an active row in chat_media_access_grant.

CREATE TABLE IF NOT EXISTS chat_media_access_grant (
    grant_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_id bigint NOT NULL,
    grantee_uid integer NOT NULL,
    grant_scope varchar(32) NOT NULL DEFAULT 'direct',
    created_at_ms bigint NOT NULL,
    revoked_at_ms bigint NOT NULL DEFAULT 0,
    CONSTRAINT uq_chat_media_access_grant UNIQUE (media_id, grantee_uid, grant_scope),
    CONSTRAINT fk_chat_media_access_grant_media FOREIGN KEY (media_id) REFERENCES chat_media_asset(media_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_chat_media_access_grant_grantee
    ON chat_media_access_grant(grantee_uid, media_id)
    WHERE revoked_at_ms = 0;
