CREATE SCHEMA IF NOT EXISTS "__OPS_SCHEMA__";
SET search_path TO "__OPS_SCHEMA__", public;

CREATE TABLE IF NOT EXISTS ops_source (
    source_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type varchar(32) NOT NULL,
    source_path varchar(512) NOT NULL,
    source_hash varchar(128) NOT NULL DEFAULT '',
    first_seen_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    metadata_json jsonb,
    CONSTRAINT uq_ops_source UNIQUE (source_type, source_path)
);

CREATE TABLE IF NOT EXISTS ops_ingest_cursor (
    cursor_key varchar(255) PRIMARY KEY,
    cursor_value jsonb,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ops_loadtest_run (
    run_id varchar(64) PRIMARY KEY,
    suite_name varchar(255) NOT NULL DEFAULT '',
    scenario_name varchar(64) NOT NULL DEFAULT '',
    test_name varchar(128) NOT NULL DEFAULT '',
    file_path varchar(512) NOT NULL,
    report_hash varchar(128) NOT NULL DEFAULT '',
    started_at timestamptz,
    finished_at timestamptz,
    status varchar(32) NOT NULL DEFAULT 'unknown',
    success_count integer NOT NULL DEFAULT 0,
    failure_count integer NOT NULL DEFAULT 0,
    summary_json jsonb,
    top_errors_json jsonb,
    phase_breakdown_json jsonb,
    preconditions_json jsonb,
    data_mutation_json jsonb,
    imported_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ops_loadtest_run_report UNIQUE (file_path, report_hash)
);

CREATE TABLE IF NOT EXISTS ops_loadtest_case (
    case_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id varchar(64) NOT NULL,
    case_name varchar(255) NOT NULL DEFAULT '',
    status varchar(32) NOT NULL DEFAULT '',
    success_count integer NOT NULL DEFAULT 0,
    failure_count integer NOT NULL DEFAULT 0,
    p50_ms double precision NOT NULL DEFAULT 0,
    p95_ms double precision NOT NULL DEFAULT 0,
    avg_ms double precision NOT NULL DEFAULT 0,
    extras_json jsonb,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ops_loadtest_case UNIQUE (run_id, case_name)
);
CREATE INDEX IF NOT EXISTS idx_ops_loadtest_case_run_id ON ops_loadtest_case(run_id);

CREATE TABLE IF NOT EXISTS ops_loadtest_error_bucket (
    bucket_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id varchar(64) NOT NULL,
    error_key varchar(255) NOT NULL,
    error_count integer NOT NULL DEFAULT 0,
    sample_message varchar(1024) NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ops_loadtest_error_bucket UNIQUE (run_id, error_key)
);
CREATE INDEX IF NOT EXISTS idx_ops_loadtest_error_key ON ops_loadtest_error_bucket(error_key);

CREATE TABLE IF NOT EXISTS ops_service_snapshot (
    snapshot_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name varchar(64) NOT NULL,
    instance_name varchar(128) NOT NULL DEFAULT '',
    observed_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    process_count integer NOT NULL DEFAULT 0,
    status varchar(32) NOT NULL DEFAULT 'unknown',
    cpu_percent double precision NOT NULL DEFAULT 0,
    memory_rss_bytes bigint NOT NULL DEFAULT 0,
    online_users integer NOT NULL DEFAULT 0,
    error_rate double precision NOT NULL DEFAULT 0,
    latency_p95_ms double precision NOT NULL DEFAULT 0,
    qps double precision NOT NULL DEFAULT 0,
    port_up boolean NOT NULL DEFAULT false,
    details_json jsonb
);
CREATE INDEX IF NOT EXISTS idx_ops_service_snapshot_service_ts ON ops_service_snapshot(service_name, observed_at);
CREATE INDEX IF NOT EXISTS idx_ops_service_snapshot_instance_ts ON ops_service_snapshot(instance_name, observed_at);

CREATE TABLE IF NOT EXISTS ops_service_metric_minute (
    metric_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name varchar(64) NOT NULL,
    instance_name varchar(128) NOT NULL DEFAULT '',
    minute_utc timestamptz NOT NULL,
    cpu_percent_avg double precision NOT NULL DEFAULT 0,
    memory_rss_bytes_avg double precision NOT NULL DEFAULT 0,
    online_users_avg double precision NOT NULL DEFAULT 0,
    qps_avg double precision NOT NULL DEFAULT 0,
    error_rate_avg double precision NOT NULL DEFAULT 0,
    latency_p95_ms_avg double precision NOT NULL DEFAULT 0,
    samples integer NOT NULL DEFAULT 0,
    CONSTRAINT uq_ops_service_metric_minute UNIQUE (service_name, instance_name, minute_utc)
);
CREATE INDEX IF NOT EXISTS idx_ops_service_metric_minute_name_ts ON ops_service_metric_minute(service_name, minute_utc);

CREATE TABLE IF NOT EXISTS ops_log_stream (
    stream_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name varchar(64) NOT NULL,
    service_instance varchar(128) NOT NULL DEFAULT '',
    source_path varchar(512) NOT NULL,
    source_type varchar(32) NOT NULL DEFAULT 'json_log',
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ops_log_stream_path UNIQUE (source_path)
);
CREATE INDEX IF NOT EXISTS idx_ops_log_stream_service ON ops_log_stream(service_name, service_instance);

CREATE TABLE IF NOT EXISTS ops_log_event_index (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name varchar(64) NOT NULL,
    service_instance varchar(128) NOT NULL DEFAULT '',
    level varchar(16) NOT NULL DEFAULT '',
    event_name varchar(128) NOT NULL DEFAULT '',
    trace_id varchar(128) NOT NULL DEFAULT '',
    request_id varchar(128) NOT NULL DEFAULT '',
    uid varchar(64) NOT NULL DEFAULT '',
    ts_utc timestamptz NOT NULL,
    duration_ms double precision NOT NULL DEFAULT 0,
    file_path varchar(512) NOT NULL,
    line_number bigint NOT NULL,
    message varchar(1024) NOT NULL DEFAULT '',
    attrs_json jsonb,
    raw_json text,
    CONSTRAINT uq_ops_log_event_line UNIQUE (file_path, line_number)
);
CREATE INDEX IF NOT EXISTS idx_ops_log_event_service_ts ON ops_log_event_index(service_name, ts_utc);
CREATE INDEX IF NOT EXISTS idx_ops_log_event_trace_id ON ops_log_event_index(trace_id);
CREATE INDEX IF NOT EXISTS idx_ops_log_event_level_ts ON ops_log_event_index(level, ts_utc);
CREATE INDEX IF NOT EXISTS idx_ops_log_event_service_instance_ts ON ops_log_event_index(service_name, service_instance, ts_utc);
CREATE INDEX IF NOT EXISTS idx_ops_log_event_request_id_ts ON ops_log_event_index(request_id, ts_utc);
CREATE INDEX IF NOT EXISTS idx_ops_log_event_name_ts ON ops_log_event_index(event_name, ts_utc);

CREATE TABLE IF NOT EXISTS ops_trace_index (
    trace_id varchar(128) PRIMARY KEY,
    first_seen_at timestamptz NOT NULL,
    last_seen_at timestamptz NOT NULL,
    services_json jsonb,
    log_count integer NOT NULL DEFAULT 0,
    span_count integer NOT NULL DEFAULT 0,
    root_service varchar(64) NOT NULL DEFAULT '',
    status varchar(32) NOT NULL DEFAULT 'active',
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ops_alert_rule (
    alert_rule_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_name varchar(128) NOT NULL,
    rule_type varchar(64) NOT NULL DEFAULT '',
    enabled boolean NOT NULL DEFAULT true,
    threshold_json jsonb,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ops_alert_rule_name UNIQUE (rule_name)
);

CREATE TABLE IF NOT EXISTS ops_platform_setting (
    setting_key varchar(128) PRIMARY KEY,
    setting_value_json jsonb,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO ops_alert_rule(rule_name, rule_type, enabled, threshold_json)
VALUES
    ('missing-service', 'service_presence', true, '{"missing_service_after_sec": 30}'::jsonb),
    ('high-error-rate', 'error_rate', true, '{"error_rate_warn": 0.25}'::jsonb),
    ('high-cpu', 'cpu', true, '{"cpu_warn": 85.0}'::jsonb)
ON CONFLICT (rule_name) DO UPDATE
SET rule_type = EXCLUDED.rule_type,
    threshold_json = EXCLUDED.threshold_json,
    enabled = EXCLUDED.enabled,
    updated_at = CURRENT_TIMESTAMP;
