/** All HTTP route constants — single source of truth */
export const ENDPOINTS = {
  // Auth
  getVarifyCode:    "/get_varifycode",
  register:         "/user_register",
  login:            "/user_login",
  authRefresh:      "/auth/refresh",
  authLogout:       "/auth/logout",
  resetPwd:         "/reset_pwd",
  getUserInfo:      "/get_user_info",
  updateProfile:    "/user_update_profile",

  // Moments
  momentsList:      "/api/moments/list",
  momentsPublish:   "/api/moments/publish",
  momentsDelete:    "/api/moments/delete",
  momentsLike:      "/api/moments/like",
  momentsComment:   "/api/moments/comment",
  momentsDetail:    "/api/moments/detail",
  momentsCommentList: "/api/moments/comment/list",
  momentsCommentLike: "/api/moments/comment/like",

  // AI / Agent
  aiChatStream:     "/ai/chat/stream",
  aiSmart:          "/ai/smart",
  aiSessionCreate:  "/ai/session/create",
  aiSessionList:    "/ai/session/list",
  aiSessionDelete:  "/ai/session/delete",
  aiSessionUpdate:  "/ai/session/update",
  aiModelList:      "/ai/model/list",
  aiModelRegister:  "/ai/model/register",
  aiModelDelete:    "/ai/model/delete",
  aiKbUpload:       "/ai/kb/upload",
  aiKbSearch:       "/ai/kb/search",
  aiKbList:         "/ai/kb/list",
  aiKbDelete:       "/ai/kb/delete",
  aiMemoryList:     "/ai/memory/list",
  aiMemoryCreate:   "/ai/memory/create",
  aiMemoryDelete:   "/ai/memory/delete",
  aiTaskList:       "/ai/task/list",
  aiTaskCreate:     "/ai/task/create",
  aiTaskCancel:     "/ai/task/cancel",
  aiTaskResume:     "/ai/task/resume",

  // Media
  mediaUpload:      "/media/upload",

  // R18
  r18Access:         "/api/r18/access",
  r18AccessAttest:   "/api/r18/access/attest",
  r18Sources:        "/api/r18/sources",
  r18Search:         "/api/r18/search",
  r18ComicDetail:    "/api/r18/comic/detail",
  r18ChapterPages:   "/api/r18/chapter/pages",
  r18Accounts:       "/api/r18/accounts",
  r18AccountSave:    "/api/r18/account/save",
  r18AccountLogin:   "/api/r18/account/login",
  r18AccountClear:   "/api/r18/account/clear",
  r18Checkin:        "/api/r18/checkin",
  r18Library:        "/api/r18/library",
  r18Favorites:      "/api/r18/favorites",
  r18FavoriteToggle: "/api/r18/favorite/toggle",
  r18FavoriteAssign: "/api/r18/favorite/assign",
  r18FolderCreate:   "/api/r18/folder/create",
  r18FolderRename:   "/api/r18/folder/rename",
  r18FolderDelete:   "/api/r18/folder/delete",
} as const
