services:
  memochat-mysql:
    image: mysql:8.0.45
    container_name: memochat-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: memo
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - D:/docker-data/memochat/mysql:/var/lib/mysql
      - ../init/mysql:/docker-entrypoint-initdb.d:ro

  memochat-redis:
    image: redis:7.2.5
    container_name: memochat-redis
    restart: unless-stopped
    command:
      - redis-server
      - --appendonly
      - "yes"
      - --requirepass
      - "123456"
    ports:
      - "6379:6379"
    volumes:
      - D:/docker-data/memochat/redis:/data

  memochat-postgres:
    image: postgres:16
    container_name: memochat-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: memochat
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: memo_pg
    ports:
      - "5432:5432"
    volumes:
      - D:/docker-data/memochat/postgres:/var/lib/postgresql/data
      - ../init/postgresql:/docker-entrypoint-initdb.d:ro

  memochat-mongo:
    image: mongo:7.0
    container_name: memochat-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "123456"
      MONGO_INITDB_DATABASE: memochat
    ports:
      - "27017:27017"
    volumes:
      - D:/docker-data/memochat/mongo:/data/db
      - ../init/mongo:/docker-entrypoint-initdb.d:ro
