services:
  memochat-redis:
    image: redis/redis-stack-server:7.2.0-v15
    container_name: memochat-redis
    restart: unless-stopped
    environment:
      REDIS_ARGS: "--appendonly yes --requirepass 123456"
    ports:
      - "6379:6379"
    volumes:
      - ${MEMOCHAT_DOCKER_DATA_ROOT:-/data/docker-data/memochat}/redis:/data

  memochat-postgres:
    image: postgres:16
    container_name: memochat-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: memochat
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: memo_pg
    ports:
      - "15432:5432"
    volumes:
      - ${MEMOCHAT_DOCKER_DATA_ROOT:-/data/docker-data/memochat}/postgres:/var/lib/postgresql/data
      - ../init/postgresql:/docker-entrypoint-initdb.d:ro

  memochat-mongo:
    image: mongo:7.0
    container_name: memochat-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "123456"
      MONGO_INITDB_DATABASE: memochat
    ports:
      - "27017:27017"
    volumes:
      - ${MEMOCHAT_DOCKER_DATA_ROOT:-/data/docker-data/memochat}/mongo:/data/db
      - ../init/mongo:/docker-entrypoint-initdb.d:ro
