CREATE SCHEMA IF NOT EXISTS "memo";
SET search_path TO "memo", public;

CREATE TABLE IF NOT EXISTS "user_id" (
    id integer PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS "user" (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid integer NOT NULL DEFAULT 0,
    name varchar(255) NOT NULL DEFAULT '',
    email varchar(255) NOT NULL DEFAULT '',
    pwd varchar(255) NOT NULL DEFAULT '',
    nick varchar(255) NOT NULL DEFAULT '',
    "desc" varchar(255) NOT NULL DEFAULT '',
    sex integer NOT NULL DEFAULT 0,
    icon varchar(255) NOT NULL DEFAULT '',
    user_id varchar(10),
    CONSTRAINT uq_user_uid UNIQUE (uid),
    CONSTRAINT uq_user_email UNIQUE (email),
    CONSTRAINT uq_user_user_id UNIQUE (user_id)
);
CREATE INDEX IF NOT EXISTS idx_user_name ON "user"(name);

CREATE TABLE IF NOT EXISTS friend (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    self_id integer NOT NULL,
    friend_id integer NOT NULL,
    back varchar(255) NOT NULL DEFAULT '',
    CONSTRAINT uq_friend_self_friend UNIQUE (self_id, friend_id)
);
CREATE INDEX IF NOT EXISTS idx_friend_self_id_friend_id ON friend(self_id, friend_id);

CREATE TABLE IF NOT EXISTS friend_apply (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_uid integer NOT NULL,
    to_uid integer NOT NULL,
    status smallint NOT NULL DEFAULT 0,
    CONSTRAINT uq_friend_apply_from_to UNIQUE (from_uid, to_uid)
);
CREATE INDEX IF NOT EXISTS idx_friend_apply_to_uid_id_from_uid ON friend_apply(to_uid, id, from_uid);

CREATE TABLE IF NOT EXISTS friend_apply_tag (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_uid integer NOT NULL,
    to_uid integer NOT NULL,
    tag varchar(64) NOT NULL,
    CONSTRAINT uq_friend_apply_tag UNIQUE (from_uid, to_uid, tag)
);
CREATE INDEX IF NOT EXISTS idx_friend_apply_tag_to_uid_from_uid_id ON friend_apply_tag(to_uid, from_uid, id);

CREATE TABLE IF NOT EXISTS friend_tag (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    self_id integer NOT NULL,
    friend_id integer NOT NULL,
    tag varchar(64) NOT NULL,
    CONSTRAINT uq_friend_tag UNIQUE (self_id, friend_id, tag)
);
CREATE INDEX IF NOT EXISTS idx_friend_tag_self_id_friend_id_id ON friend_tag(self_id, friend_id, id);

CREATE TABLE IF NOT EXISTS chat_group (
    group_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_code varchar(10),
    name varchar(64) NOT NULL,
    owner_uid integer NOT NULL,
    announcement text,
    member_limit integer NOT NULL DEFAULT 200,
    is_all_muted boolean NOT NULL DEFAULT false,
    status smallint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    icon varchar(512),
    CONSTRAINT uq_chat_group_code UNIQUE (group_code)
);
CREATE INDEX IF NOT EXISTS idx_chat_group_owner_uid ON chat_group(owner_uid);
CREATE INDEX IF NOT EXISTS idx_chat_group_status ON chat_group(status);

CREATE TABLE IF NOT EXISTS chat_group_member (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id bigint NOT NULL,
    uid integer NOT NULL,
    role smallint NOT NULL DEFAULT 0,
    mute_until bigint NOT NULL DEFAULT 0,
    join_source smallint NOT NULL DEFAULT 0,
    status smallint NOT NULL DEFAULT 1,
    joined_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_chat_group_member UNIQUE (group_id, uid)
);
CREATE INDEX IF NOT EXISTS idx_chat_group_member_uid ON chat_group_member(uid);

CREATE TABLE IF NOT EXISTS chat_group_apply (
    apply_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id bigint NOT NULL,
    applicant_uid integer NOT NULL,
    inviter_uid integer NOT NULL DEFAULT 0,
    type smallint NOT NULL DEFAULT 0,
    status smallint NOT NULL DEFAULT 0,
    reason varchar(255) NOT NULL DEFAULT '',
    reviewer_uid integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_chat_group_apply_group_id ON chat_group_apply(group_id);
CREATE INDEX IF NOT EXISTS idx_chat_group_apply_applicant_uid ON chat_group_apply(applicant_uid);

CREATE TABLE IF NOT EXISTS chat_group_msg (
    server_msg_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    msg_id varchar(64) NOT NULL,
    group_id bigint NOT NULL,
    group_seq bigint NOT NULL DEFAULT 0,
    from_uid integer NOT NULL,
    msg_type varchar(32) NOT NULL DEFAULT 'text',
    content text NOT NULL DEFAULT '',
    mentions_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    reply_to_server_msg_id bigint NOT NULL DEFAULT 0,
    forward_meta_json jsonb,
    edited_at_ms bigint NOT NULL DEFAULT 0,
    deleted_at_ms bigint NOT NULL DEFAULT 0,
    created_at bigint NOT NULL DEFAULT 0,
    CONSTRAINT uq_chat_group_msg_group_msg_id UNIQUE (group_id, msg_id),
    CONSTRAINT uq_chat_group_msg_group_seq UNIQUE (group_id, group_seq)
);
CREATE INDEX IF NOT EXISTS idx_chat_group_msg_group_id_msg_id ON chat_group_msg(group_id, msg_id DESC);
CREATE INDEX IF NOT EXISTS idx_chat_group_msg_group_seq ON chat_group_msg(group_id, group_seq);

CREATE TABLE IF NOT EXISTS chat_group_msg_ext (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    msg_id varchar(64) NOT NULL,
    file_name varchar(255) NOT NULL DEFAULT '',
    mime varchar(128) NOT NULL DEFAULT '',
    size bigint NOT NULL DEFAULT 0,
    CONSTRAINT uq_chat_group_msg_ext UNIQUE (msg_id)
);

CREATE TABLE IF NOT EXISTS chat_private_msg (
    msg_id varchar(64) PRIMARY KEY,
    conv_uid_min integer NOT NULL,
    conv_uid_max integer NOT NULL,
    from_uid integer NOT NULL,
    to_uid integer NOT NULL,
    content text NOT NULL DEFAULT '',
    reply_to_server_msg_id bigint NOT NULL DEFAULT 0,
    forward_meta_json jsonb,
    edited_at_ms bigint NOT NULL DEFAULT 0,
    deleted_at_ms bigint NOT NULL DEFAULT 0,
    created_at bigint NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_chat_private_msg_dialog_id_msg_id ON chat_private_msg(conv_uid_min, conv_uid_max, msg_id DESC);

CREATE TABLE IF NOT EXISTS chat_dialog (
    dialog_id varchar(64) PRIMARY KEY,
    owner_uid integer NOT NULL,
    peer_uid integer NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_msg_id bigint NOT NULL DEFAULT 0,
    unread_count integer NOT NULL DEFAULT 0,
    CONSTRAINT uq_chat_dialog UNIQUE (owner_uid, peer_uid)
);

CREATE TABLE IF NOT EXISTS chat_dialog_meta (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dialog_id varchar(64) NOT NULL,
    meta_key varchar(64) NOT NULL,
    meta_value varchar(255) NOT NULL DEFAULT '',
    CONSTRAINT uq_chat_dialog_meta UNIQUE (dialog_id, meta_key)
);

CREATE TABLE IF NOT EXISTS chat_private_read_state (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid integer NOT NULL,
    peer_uid integer NOT NULL,
    read_ts bigint NOT NULL DEFAULT 0,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_chat_private_read_state UNIQUE (uid, peer_uid)
);
CREATE INDEX IF NOT EXISTS idx_chat_private_read_state_peer_uid ON chat_private_read_state(peer_uid, uid);

CREATE TABLE IF NOT EXISTS chat_group_read_state (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid integer NOT NULL,
    group_id bigint NOT NULL,
    read_ts bigint NOT NULL DEFAULT 0,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_chat_group_read_state UNIQUE (uid, group_id)
);
CREATE INDEX IF NOT EXISTS idx_chat_group_read_state_group_uid ON chat_group_read_state(group_id, uid);

CREATE TABLE IF NOT EXISTS chat_group_admin_permission (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id bigint NOT NULL,
    uid integer NOT NULL,
    permission_mask integer NOT NULL DEFAULT 0,
    CONSTRAINT uq_chat_group_admin_permission UNIQUE (group_id, uid)
);

CREATE TABLE IF NOT EXISTS chat_media_asset (
    media_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_key varchar(64) NOT NULL,
    owner_uid integer NOT NULL,
    media_type varchar(16) NOT NULL,
    origin_file_name varchar(255) NOT NULL,
    mime varchar(127) NOT NULL DEFAULT '',
    size_bytes bigint NOT NULL DEFAULT 0,
    storage_provider varchar(32) NOT NULL DEFAULT 'local',
    storage_path varchar(1024) NOT NULL,
    created_at_ms bigint NOT NULL,
    deleted_at_ms bigint NOT NULL DEFAULT 0,
    status smallint NOT NULL DEFAULT 1,
    CONSTRAINT uq_chat_media_asset_key UNIQUE (media_key)
);
CREATE INDEX IF NOT EXISTS idx_chat_media_asset_owner_created ON chat_media_asset(owner_uid, created_at_ms);

CREATE TABLE IF NOT EXISTS chat_call_session (
    call_id varchar(64) PRIMARY KEY,
    room_name varchar(128) NOT NULL,
    call_type varchar(16) NOT NULL,
    caller_uid integer NOT NULL,
    callee_uid integer NOT NULL,
    state varchar(32) NOT NULL,
    started_at_ms bigint NOT NULL,
    accepted_at_ms bigint NOT NULL DEFAULT 0,
    ended_at_ms bigint NOT NULL DEFAULT 0,
    expires_at_ms bigint NOT NULL DEFAULT 0,
    duration_sec integer NOT NULL DEFAULT 0,
    reason varchar(64) NOT NULL DEFAULT '',
    trace_id varchar(64) NOT NULL DEFAULT '',
    updated_at_ms bigint NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_chat_call_session_caller ON chat_call_session(caller_uid, started_at_ms);
CREATE INDEX IF NOT EXISTS idx_chat_call_session_callee ON chat_call_session(callee_uid, started_at_ms);
CREATE INDEX IF NOT EXISTS idx_chat_call_session_state ON chat_call_session(state, updated_at_ms);
