CREATE SCHEMA IF NOT EXISTS "memo_ops";
SET search_path TO "memo_ops", public;

CREATE TABLE IF NOT EXISTS ops_source (
    source_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type varchar(32) NOT NULL,
    source_path varchar(512) NOT NULL,
    source_hash varchar(128) NOT NULL DEFAULT '',
    first_seen_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    metadata_json jsonb,
    CONSTRAINT uq_ops_source UNIQUE (source_type, source_path)
);

CREATE TABLE IF NOT EXISTS ops_ingest_cursor (
    cursor_key varchar(255) PRIMARY KEY,
    cursor_value jsonb,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ops_loadtest_run (
    run_id varchar(64) PRIMARY KEY,
    suite_name varchar(255) NOT NULL DEFAULT '',
    scenario_name varchar(64) NOT NULL DEFAULT '',
    test_name varchar(128) NOT NULL DEFAULT '',
    file_path varchar(512) NOT NULL,
    report_hash varchar(128) NOT NULL DEFAULT '',
    started_at timestamptz,
    finished_at timestamptz,
    status varchar(32) NOT NULL DEFAULT 'unknown',
    success_count integer NOT NULL DEFAULT 0,
    failure_count integer NOT NULL DEFAULT 0,
    summary_json jsonb,
    top_errors_json jsonb,
    phase_breakdown_json jsonb,
    preconditions_json jsonb,
    data_mutation_json jsonb,
    imported_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ops_loadtest_run_report UNIQUE (file_path, report_hash)
);

CREATE TABLE IF NOT EXISTS ops_loadtest_case (
    case_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id varchar(64) NOT NULL,
    case_name varchar(255) NOT NULL DEFAULT '',
    status varchar(32) NOT NULL DEFAULT '',
    success_count integer NOT NULL DEFAULT 0,
    failure_count integer NOT NULL DEFAULT 0,
    p50_ms double precision NOT NULL DEFAULT 0,
    p95_ms double precision NOT NULL DEFAULT 0,
    avg_ms double precision NOT NULL DEFAULT 0,
    extras_json jsonb,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ops_loadtest_case UNIQUE (run_id, case_name)
);

CREATE TABLE IF NOT EXISTS ops_loadtest_error_bucket (
    bucket_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id varchar(64) NOT NULL,
    error_key varchar(255) NOT NULL,
    error_count integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ops_loadtest_error_bucket UNIQUE (run_id, error_key)
);

CREATE TABLE IF NOT EXISTS ops_service_snapshot (
    snapshot_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name varchar(128) NOT NULL,
    instance_name varchar(128) NOT NULL DEFAULT '',
    observed_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cpu_percent double precision NOT NULL DEFAULT 0,
    rss_bytes bigint NOT NULL DEFAULT 0,
    online_users integer NOT NULL DEFAULT 0,
    qps double precision NOT NULL DEFAULT 0,
    error_rate double precision NOT NULL DEFAULT 0,
    latency_p95_ms double precision NOT NULL DEFAULT 0,
    up_status boolean NOT NULL DEFAULT false,
    payload_json jsonb
);

CREATE TABLE IF NOT EXISTS ops_service_metric_minute (
    metric_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name varchar(128) NOT NULL,
    metric_name varchar(128) NOT NULL,
    bucket_minute timestamptz NOT NULL,
    metric_value double precision NOT NULL DEFAULT 0,
    labels_json jsonb,
    CONSTRAINT uq_ops_service_metric_minute UNIQUE (service_name, metric_name, bucket_minute)
);

CREATE TABLE IF NOT EXISTS ops_log_stream (
    stream_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name varchar(128) NOT NULL,
    file_path varchar(512) NOT NULL,
    first_seen_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ops_log_stream UNIQUE (service_name, file_path)
);

CREATE TABLE IF NOT EXISTS ops_log_event_index (
    event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stream_id bigint NOT NULL,
    service_name varchar(128) NOT NULL,
    level varchar(32) NOT NULL DEFAULT '',
    event_name varchar(255) NOT NULL DEFAULT '',
    trace_id varchar(64) NOT NULL DEFAULT '',
    request_id varchar(64) NOT NULL DEFAULT '',
    occurred_at timestamptz,
    offset_hint bigint NOT NULL DEFAULT 0,
    payload_json jsonb
);

CREATE TABLE IF NOT EXISTS ops_trace_index (
    trace_pk bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id varchar(64) NOT NULL,
    service_name varchar(128) NOT NULL DEFAULT '',
    root_span varchar(255) NOT NULL DEFAULT '',
    started_at timestamptz,
    duration_ms double precision NOT NULL DEFAULT 0,
    payload_json jsonb,
    CONSTRAINT uq_ops_trace_index UNIQUE (trace_id, service_name, root_span)
);

CREATE TABLE IF NOT EXISTS ops_alert_rule (
    rule_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_name varchar(128) NOT NULL,
    rule_type varchar(64) NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    threshold_json jsonb,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ops_alert_rule UNIQUE (rule_name)
);

CREATE TABLE IF NOT EXISTS ops_platform_setting (
    setting_key varchar(128) PRIMARY KEY,
    setting_value jsonb,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
