apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: memochat-staging

bases:
  - ../../base
  - ../../etcd
  - ../../backend
  - ../../infra

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: memochat-gateserver
      spec:
        replicas: 2
    target:
      kind: Deployment
      name: memochat-gateserver
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: memochat-statusserver
      spec:
        replicas: 2
    target:
      kind: Deployment
      name: memochat-statusserver
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: memochat-varifyserver
      spec:
        replicas: 2
    target:
      kind: Deployment
      name: memochat-varifyserver
  - patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: memochat-chatserver
      spec:
        replicas: 3
    target:
      kind: StatefulSet
      name: memochat-chatserver

configMapGenerator:
  - name: memochat-config
    behavior: merge
    literals:
      - LOG_LEVEL=info
      - ETCD_ENDPOINTS=http://memochat-etcd:2379

images:
  - name: memochat/gateserver
    newTag: staging-latest
  - name: memochat/statusserver
    newTag: staging-latest
  - name: memochat/chatserver
    newTag: staging-latest
  - name: memochat/varifyserver
    newTag: staging-latest
